user_footer = footer.json
user_name = teefs
user_libs = -lteefs -los -lc
user_includes =
user_objs = teefs.o
user_cflags = -DCONFIG_TEEFS_MAX_NAMELEN=64
user_ldflags =

include ../../common/container.mk
