/*
 * [Rebellions Inc.]("Rebellions") CONFIDENTIAL
 * Unpublished Copyright (c) 2025 [Rebellions Inc.], All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of Rebellions.
 * The intellectual and technical concepts contained herein are proprietary to Rebellions
 * and may be covered by Republic of Korea, U.S., and other countries' Patents, patents
 * in process, and are protected by trade secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material is strictly forbidden
 * unless prior written permission is obtained from Rebellions. Access to the source code
 * contained herein is hereby forbidden to anyone except current Rebellions employees, managers
 * or contractors who have executed Confidentiality and Non-disclosure agreements explicitly
 * covering such access.
 *
 * The copyright notice above does not evidence any actual or intended publication or disclosure
 * of this source code, which includes information that is confidential and/or proprietary, and
 * is a trade secret, of Rebellions.
 *
 * ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC PERFORMANCE, OR PUBLIC DISPLAY OF OR
 * THROUGH USE OF THIS SOURCE CODE WITHOUT THE EXPRESS WRITTEN CONSENT OF REBELLIONS IS STRICTLY
 * PROHIBITED, AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR
 * POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
 * TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING
 * THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.
 */

#include <stdint.h>
#include <stdio.h>

#include "rbcm_reg_addr.h"
#include "rbcm_reg_reset.h"
#include "rl_errors.h"
#include "rbcm_reg_access_test.h"
#include "rl_utils.h"

/*
 * This register is skipped in all Register Access Tests
 * since accessing it directly impacts normal operation
 */
#define SKIP_REG_ACC_SPECIFIC_REG

struct rbcm_reg_access_test rbcm_reg_acc_tests[] = {
	RBCM_REG_ACCESS_ENTRY(GLOBAL_IP_INFO0, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_IP_INFO1, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_IP_INFO2, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_DESIGN_INFO0, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_DESIGN_INFO1, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_COMMON_RPT, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_COMMON_REG, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_INFO, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_CTL, RO),
#ifndef SKIP_REG_ACC_SPECIFIC_REG
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_CONFIG, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_PORT_CONFIG, RW),
#endif
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_INTR_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_INTR_MASK, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_INTR_CLR, RO),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_RTBL_IN_0, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_RTBL_IN_1, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_RTBL_OUT_0, RW),
	RBCM_REG_ACCESS_ENTRY(GLOBAL_RBC_RTBL_OUT_1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_WINDOW_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_PORT_ERR_INTR_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_ERR_INTR_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_INTR_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_0, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_1, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_2, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_3, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_4, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_5, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_6, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_7, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_8, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_9, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_10, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TIMEOUT_STATUS_11, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_SEL, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_ACC, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_ACC_CHK, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_RET_0, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_RET_1, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_RET_2, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_RET_3, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_VE_0, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_VE_1, RO),
#ifndef SKIP_REG_ACC_SPECIFIC_REG
	RBCM_REG_ACCESS_ENTRY(GLUE_TTREG_VE_2, RO),
#endif
	RBCM_REG_ACCESS_ENTRY(GLUE_LB_CTL, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_CTL, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_W_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_W_CONFIG1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_W_CONFIG2, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_W_CONFIG3, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_R_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_R_CONFIG1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_R_CONFIG2, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P0_R_CONFIG3, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_W_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_W_CONFIG1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_W_CONFIG2, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_W_CONFIG3, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_R_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_R_CONFIG1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_R_CONFIG2, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P1_R_CONFIG3, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_W_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_W_CONFIG1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_W_CONFIG2, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_W_CONFIG3, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_R_CONFIG0, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_R_CONFIG1, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_R_CONFIG2, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_USER_TRANSACTION_P2_R_CONFIG3, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_RBC_GLUE_CTL_0, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_RBC_GLUE_CTL_1, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_RBC_GLUE_CTL_2, RO),
	RBCM_REG_ACCESS_ENTRY(GLUE_BP_SEL, RW),
	RBCM_REG_ACCESS_ENTRY(GLUE_TRL_SEL, RW),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_IP_INFO0, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_IP_INFO1, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_IP_INFO2, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_IP_INFO3, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_CONFIGURE_EN, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_CLEAR_SET, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_CONFIGURE_PERIOD, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_CONFIGURE_FLUSH, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_CONFIGURE_TRGT01, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_CONFIGURE_TRGT23, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_BP_MON_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG0, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG1, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG2, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG3, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG4, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG5, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG6, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG7, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG8, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG9, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG10, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG11, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG12, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG13, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG14, RO),
	RBCM_REG_ACCESS_ENTRY(PM0_PROFILE_PKG15, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_IP_INFO0, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_IP_INFO1, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_IP_INFO2, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_IP_INFO3, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_CONFIGURE_EN, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_CLEAR_SET, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_CONFIGURE_PERIOD, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_CONFIGURE_FLUSH, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_CONFIGURE_TRGT01, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_CONFIGURE_TRGT23, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_BP_MON_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG0, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG1, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG2, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG3, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG4, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG5, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG6, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG7, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG8, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG9, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG10, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG11, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG12, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG13, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG14, RO),
	RBCM_REG_ACCESS_ENTRY(PM1_PROFILE_PKG15, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_IP_INFO0, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_IP_INFO1, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_IP_INFO2, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_IP_INFO3, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_CONFIGURE_EN, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_CLEAR_SET, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_CONFIGURE_PERIOD, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_CONFIGURE_FLUSH, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_CONFIGURE_TRGT01, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_CONFIGURE_TRGT23, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_BP_MON_STATUS, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG0, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG1, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG2, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG3, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG4, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG5, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG6, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG7, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG8, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG9, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG10, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG11, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG12, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG13, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG14, RO),
	RBCM_REG_ACCESS_ENTRY(PM2_PROFILE_PKG15, RO)};

static int32_t verify_register(uint64_t address, uint32_t expected_value,
							   uint32_t mask)
{
	uint32_t *p_reg = (uint32_t *)(uintptr_t)address;
	uint32_t resulted_value = *p_reg;

	if ((resulted_value & mask) != (expected_value & mask)) {
		printf("Mismatch 0x%08lx (Exp 0x%08x != 0x%08x Result)\r\n",
			   (unsigned long)address, expected_value & mask,
			   resulted_value & mask);
		return 1;
	} else
		return 0;
}

int32_t rbcm_run_reg_rst_test(enum rbcm_module idx)
{
	int32_t ret = 0;
	uint64_t base;

	base = get_rbcm_base(idx);
	if (base == 0)
		return RL_BADARG;

	for (int i = 0; i < ARRAY_SIZE(rbcm_reg_acc_tests); i++) {
		struct rbcm_reg_access_test *test = &rbcm_reg_acc_tests[i];

		ret += verify_register(base + test->offset,
							   test->expected_value, test->mask);
	}

	return ret;
}

int32_t rbcm_run_reg_acc_test(enum rbcm_module idx)
{
	int32_t ret = 0;
	uint64_t base;

	base = get_rbcm_base(idx);
	if (base == 0)
		return RL_BADARG;

	for (int i = 0; i < ARRAY_SIZE(rbcm_reg_acc_tests); i++) {
		struct rbcm_reg_access_test *test = &rbcm_reg_acc_tests[i];

		if (test->access != RW)
			continue;

		rl_writel(test->test_val, (uint32_t *)(base + test->offset));
		ret += verify_register(base + test->offset,
							   test->test_val, test->mask);
		/* Reset the register to its expected value */
		rl_writel(test->expected_value, (uint32_t *)(base + test->offset));
	}

	return ret;
}

