CONFIG_CMRT_V1=y
CONFIG_MULTITHREADING=n
CONFIG_SUPERVISOR_MODE=y
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_CMRT_PKE=y
CONFIG_CMRT_AES=y
CONFIG_TEEFS=y
CONFIG_TEEFS_MAX_INSTANCES=2
CONFIG_TEEFS_MAX_PAGES=31
CONFIG_TEEFS_MAX_FILES=4
CONFIG_TEEFS_MAX_PAGE_SIZE=7
CONFIG_TEEFS_MAX_DIRS=1
CONFIG_TEEFS_MAX_CACHE_PAGES=4
CONFIG_TEEFS_MAX_BAD_BLOCKS=1
CONFIG_TEEFS_MAX_NAMELEN=69
CONFIG_CMRT_TEEDEV_RAM=y
CONFIG_TEEDEV_RAM_BLOCK_SIZE=9
CONFIG_TEEDEV_RAM_PAGE_SIZE=7
CONFIG_TEEDEV_RAM_CACHE_PAGES=1
CONFIG_CMRT_TEEDEV_OTP=y
CONFIG_TEEDEV_OTP_BLOCK_SIZE=9
CONFIG_TEEDEV_OTP_PAGE_SIZE=7
CONFIG_TEEDEV_OTP_CACHE_PAGES=4
CONFIG_CMRT_FIPS_140_MODE=y
CONFIG_CMRT_RSA=y
CONFIG_CMRT_RSA_CRT=y
CONFIG_CMRT_FFDH=n
CONFIG_CMRT_PKE_SECP256K1=n
CONFIG_CMRT_PKE_BRAINPOOL_P192R1=n
CONFIG_CMRT_PKE_BRAINPOOL_P224R1=n
CONFIG_CMRT_PKE_BRAINPOOL_P256R1=n
CONFIG_CMRT_PKE_BRAINPOOL_P320R1=n
CONFIG_CMRT_PKE_BRAINPOOL_P384R1=n
CONFIG_CMRT_PKE_BRAINPOOL_P512R1=n
CONFIG_CMRT_PKE_BRAINPOOL_P192T1=n
CONFIG_CMRT_PKE_BRAINPOOL_P224T1=n
CONFIG_CMRT_PKE_BRAINPOOL_P256T1=n
CONFIG_CMRT_PKE_BRAINPOOL_P320T1=n
CONFIG_CMRT_PKE_BRAINPOOL_P384T1=n
CONFIG_CMRT_PKE_BRAINPOOL_P512T1=n
CONFIG_CMRT_PKE_ED25519_CURVE=n
CONFIG_CMRT_PKE_X25519_CURVE=n
CONFIG_CMRT_PKE_X448_CURVE=n
CONFIG_CMRT_PKE_ED448_CURVE=n
CONFIG_CMRT_PKE_FRP256_CURVE=n
# make RELEASE_BUILD=1 unsets these
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_DEBUG=y
