# List of working directories
REBELH_TOP=`pwd`

# Binary directories
BINARY_TOP="$REBELH_TOP/binaries"
BINARY_BOOTLOADER_BOOTROM="$BINARY_TOP/BootLoader_CP"
BINARY_BOOTLOADER_TF_A=$BINARY_BOOTLOADER_BOOTROM
BINARY_FREERTOS_CP="$BINARY_TOP/FreeRTOS_CP"
BINARY_FREERTOS_CP1="$BINARY_TOP/FreeRTOS_CP1"
BINARY_FREERTOS_PCIE="$BINARY_TOP/FreeRTOS_PCIE"
BINARY_BOOTLOADER_ROT="$BINARY_TOP/BootLoader_ROT"
BINARY_CONTAINER_ROT="$BINARY_TOP/Container_ROT"
BINARY_XIP_ROT="$BINARY_TOP/XIP_ROT"
BINARY_ZEPHYR_ROT="$BINARY_TOP/Zephyr_ROT"

# Bootloader directories
BOOTLOADER_TOP="$REBELH_TOP/bootloader"
BOOTLOADER_BOOTROM="$BOOTLOADER_TOP/cp/fboot"
BOOTLOADER_TF_A="$BOOTLOADER_TOP/cp/tf-a"
BOOTLOADER_CMRT="$BOOTLOADER_TOP/rot/cmrt-zephyr-2.0.36"
BOOTLOADER_CMRT_SAMPLE="$BOOTLOADER_CMRT/samples/cmrt"
BOOTLOADER_SBOOT_S="$BOOTLOADER_CMRT_SAMPLE/sboot"
BOOTLOADER_TBOOT_S="$BOOTLOADER_CMRT_SAMPLE/supervisors/mw"
BOOTLOADER_CONTAINER="$BOOTLOADER_CMRT_SAMPLE/perso"

# FreeRTOS directories
FREERTOS_TOP="$REBELH_TOP/osl/FreeRTOS/Source"
