/*
 * [Rebellions Inc.]("Rebellions") CONFIDENTIAL
 * Unpublished Copyright (c) 2021-2023 [Rebellions Inc.], All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of Rebellions.
 * The intellectual and technical concepts contained herein are proprietary to Rebellions
 * and may be covered by Republic of Korea, U.S., and other countries' Patents, patents
 * in process, and are protected by trade secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material is strictly forbidden
 * unless prior written permission is obtained from Rebellions. Access to the source code
 * contained herein is hereby forbidden to anyone except current Rebellions employees, managers
 * or contractors who have executed Confidentiality and Non-disclosure agreements explicitly
 * covering such access.
 *
 * The copyright notice above does not evidence any actual or intended publication or disclosure
 * of this source code, which includes information that is confidential and/or proprietary, and
 * is a trade secret, of Rebellions.
 *
 * ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC PERFORMANCE, OR PUBLIC DISPLAY OF OR
 * THROUGH USE OF THIS SOURCE CODE WITHOUT THE EXPRESS WRITTEN CONSENT OF REBELLIONS IS STRICTLY
 * PROHIBITED, AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR
 * POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
 * TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING
 * THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.
 */

#ifndef _CP_INTERRUPT_H_
#define _CP_INTERRUPT_H_

#include "gic.h"
#include "gic.h"
//#include "rbln/utils.h"
#include "rl_utils.h"
#include "common/exec_id.h"

#define metal_interrupt_enable(intc, id) arm_gic_v3_irq_enable((id))

union irq_info {
	struct  __attribute__((packed, aligned(8))) {
		union exec_id	exec_id;
		uint8_t			hw_id;
		uint8_t			cmd_type;
		uint8_t			task_credit;
		uint8_t			tlb_credit;
	};
	uint64_t bits;
};

/* Interrupt ID Table */
enum rl_int_id_tbl {

	INT_ID_EAST_BUS_0 = 72,
	INT_ID_EAST_BUS_1,
	INT_ID_EAST_BUS_2,

	INT_ID_NOC_CFG_IDLE = 80,
	INT_ID_NOC_CFG_ACTIVE,
	INT_ID_NOC_CFG_ERR,

	INT_ID_DRAM0_CTL = 96,
	INT_ID_DRAM0_PHY,
	INT_ID_DRAM1_CTL,
	INT_ID_DRAM1_PHY,
	INT_ID_DRAM2_CTL,
	INT_ID_DRAM2_PHY,
	INT_ID_DRAM3_CTL,
	INT_ID_DRAM3_PHY,

	INT_ID_CMGR = 892,

	INT_ID_RBDMA0_ERR = 977,
	INT_ID_RBDMA1,

	INT_ID_DNC0_EXCEPTION = 410,
	INT_ID_DNC0_COMPUTE,
	INT_ID_DNC0_UDMA,
	INT_ID_DNC0_UDMA_LP,
	INT_ID_DNC0_UDMA_ST,
	INT_ID_DNC0_TASK16B,

	INT_ID_DNC1_EXCEPTION = 422,
	INT_ID_DNC1_COMPUTE,
	INT_ID_DNC1_UDMA,
	INT_ID_DNC1_UDMA_LP,
	INT_ID_DNC1_UDMA_ST,
	INT_ID_DNC1_TASK16B,

	INT_ID_DNC2_EXCEPTION = 416,
	INT_ID_DNC2_COMPUTE,
	INT_ID_DNC2_UDMA,
	INT_ID_DNC2_UDMA_LP,
	INT_ID_DNC2_UDMA_ST,
	INT_ID_DNC2_TASK16B,

	INT_ID_DNC3_EXCEPTION = 428,
	INT_ID_DNC3_COMPUTE,
	INT_ID_DNC3_UDMA,
	INT_ID_DNC3_UDMA_LP,
	INT_ID_DNC3_UDMA_ST,
	INT_ID_DNC3_TASK16B,

	INT_ID_DNC4_EXCEPTION = 434,
	INT_ID_DNC4_COMPUTE,
	INT_ID_DNC4_UDMA,
	INT_ID_DNC4_UDMA_LP,
	INT_ID_DNC4_UDMA_ST,
	INT_ID_DNC4_TASK16B,

	INT_ID_DNC5_EXCEPTION = 446,
	INT_ID_DNC5_COMPUTE,
	INT_ID_DNC5_UDMA,
	INT_ID_DNC5_UDMA_LP,
	INT_ID_DNC5_UDMA_ST,
	INT_ID_DNC5_TASK16B,

	INT_ID_DNC6_EXCEPTION = 440,
	INT_ID_DNC6_COMPUTE,
	INT_ID_DNC6_UDMA,
	INT_ID_DNC6_UDMA_LP,
	INT_ID_DNC6_UDMA_ST,
	INT_ID_DNC6_TASK16B,

	INT_ID_DNC7_EXCEPTION = 452,
	INT_ID_DNC7_COMPUTE,
	INT_ID_DNC7_UDMA,
	INT_ID_DNC7_UDMA_LP,
	INT_ID_DNC7_UDMA_ST,
	INT_ID_DNC7_TASK16B,

	INT_ID_DNC8_EXCEPTION = 570,
	INT_ID_DNC8_COMPUTE,
	INT_ID_DNC8_UDMA,
	INT_ID_DNC8_UDMA_LP,
	INT_ID_DNC8_UDMA_ST,
	INT_ID_DNC8_TASK16B,

	INT_ID_DNC9_EXCEPTION = 582,
	INT_ID_DNC9_COMPUTE,
	INT_ID_DNC9_UDMA,
	INT_ID_DNC9_UDMA_LP,
	INT_ID_DNC9_UDMA_ST,
	INT_ID_DNC9_TASK16B,

	INT_ID_DNC10_EXCEPTION = 576,
	INT_ID_DNC10_COMPUTE,
	INT_ID_DNC10_UDMA,
	INT_ID_DNC10_UDMA_LP,
	INT_ID_DNC10_UDMA_ST,
	INT_ID_DNC10_TASK16B,

	INT_ID_DNC11_EXCEPTION = 588,
	INT_ID_DNC11_COMPUTE,
	INT_ID_DNC11_UDMA,
	INT_ID_DNC11_UDMA_LP,
	INT_ID_DNC11_UDMA_ST,
	INT_ID_DNC11_TASK16B,

	INT_ID_DNC12_EXCEPTION = 594,
	INT_ID_DNC12_COMPUTE,
	INT_ID_DNC12_UDMA,
	INT_ID_DNC12_UDMA_LP,
	INT_ID_DNC12_UDMA_ST,
	INT_ID_DNC12_TASK16B,

	INT_ID_DNC13_EXCEPTION = 606,
	INT_ID_DNC13_COMPUTE,
	INT_ID_DNC13_UDMA,
	INT_ID_DNC13_UDMA_LP,
	INT_ID_DNC13_UDMA_ST,
	INT_ID_DNC13_TASK16B,

	INT_ID_DNC14_EXCEPTION = 600,
	INT_ID_DNC14_COMPUTE,
	INT_ID_DNC14_UDMA,
	INT_ID_DNC14_UDMA_LP,
	INT_ID_DNC14_UDMA_ST,
	INT_ID_DNC14_TASK16B,

	INT_ID_DNC15_EXCEPTION = 612,
	INT_ID_DNC15_COMPUTE,
	INT_ID_DNC15_UDMA,
	INT_ID_DNC15_UDMA_LP,
	INT_ID_DNC15_UDMA_ST,
	INT_ID_DNC15_TASK16B,

	INT_ID_SHM0_EXCEPTION = 458,		//INT_ID [458], SPI [426]
	INT_ID_SHM0_INFORMATIONAL,
	INT_ID_SHM1_EXCEPTION,
	INT_ID_SHM1_INFORMATIONAL,
	INT_ID_SHM2_EXCEPTION,
	INT_ID_SHM2_INFORMATIONAL,
	INT_ID_SHM3_EXCEPTION,
	INT_ID_SHM3_INFORMATIONAL,
	INT_ID_SHM4_EXCEPTION,
	INT_ID_SHM4_INFORMATIONAL,
	INT_ID_SHM5_EXCEPTION,
	INT_ID_SHM5_INFORMATIONAL,
	INT_ID_SHM6_EXCEPTION,
	INT_ID_SHM6_INFORMATIONAL,
	INT_ID_SHM7_EXCEPTION,
	INT_ID_SHM7_INFORMATIONAL,
	INT_ID_SHM8_EXCEPTION,
	INT_ID_SHM8_INFORMATIONAL,
	INT_ID_SHM9_EXCEPTION,
	INT_ID_SHM9_INFORMATIONAL,
	INT_ID_SHM10_EXCEPTION,
	INT_ID_SHM10_INFORMATIONAL,
	INT_ID_SHM11_EXCEPTION,
	INT_ID_SHM11_INFORMATIONAL,
	INT_ID_SHM12_EXCEPTION,
	INT_ID_SHM12_INFORMATIONAL,
	INT_ID_SHM13_EXCEPTION,
	INT_ID_SHM13_INFORMATIONAL,
	INT_ID_SHM14_EXCEPTION,
	INT_ID_SHM14_INFORMATIONAL,
	INT_ID_SHM15_EXCEPTION,
	INT_ID_SHM15_INFORMATIONAL,

	INT_ID_SHM16_EXCEPTION = 618,
	INT_ID_SHM16_INFORMATIONAL,
	INT_ID_SHM17_EXCEPTION,
	INT_ID_SHM17_INFORMATIONAL,
	INT_ID_SHM18_EXCEPTION,
	INT_ID_SHM18_INFORMATIONAL,
	INT_ID_SHM19_EXCEPTION,
	INT_ID_SHM19_INFORMATIONAL,
	INT_ID_SHM20_EXCEPTION,
	INT_ID_SHM20_INFORMATIONAL,
	INT_ID_SHM21_EXCEPTION,
	INT_ID_SHM21_INFORMATIONAL,
	INT_ID_SHM22_EXCEPTION,
	INT_ID_SHM22_INFORMATIONAL,
	INT_ID_SHM23_EXCEPTION,
	INT_ID_SHM23_INFORMATIONAL,
	INT_ID_SHM24_EXCEPTION,
	INT_ID_SHM24_INFORMATIONAL,
	INT_ID_SHM25_EXCEPTION,
	INT_ID_SHM25_INFORMATIONAL,
	INT_ID_SHM26_EXCEPTION,
	INT_ID_SHM26_INFORMATIONAL,
	INT_ID_SHM27_EXCEPTION,
	INT_ID_SHM27_INFORMATIONAL,
	INT_ID_SHM28_EXCEPTION,
	INT_ID_SHM28_INFORMATIONAL,
	INT_ID_SHM29_EXCEPTION,
	INT_ID_SHM29_INFORMATIONAL,
	INT_ID_SHM30_EXCEPTION,
	INT_ID_SHM30_INFORMATIONAL,
	INT_ID_SHM31_EXCEPTION,
	INT_ID_SHM31_INFORMATIONAL,

	INT_ID_MGLUE_EXCEPTION	= 490,		//INT_ID [490] SPI[458]

	TBU_DGLUE_CL0_CH0_ERR_IRPT = 779,
	TBU_DGLUE_CL0_CH1_ERR_IRPT,
	TBU_DGLUE_CL0_CH2_ERR_IRPT = 670,
	TBU_DGLUE_CL0_CH3_ERR_IRPT = 754,
	TBU_DGLUE_CL1_CH0_ERR_IRPT = 802,
	TBU_DGLUE_CL1_CH1_ERR_IRPT,
	TBU_DGLUE_CL1_CH2_ERR_IRPT = 706,
	TBU_DGLUE_CL1_CH3_ERR_IRPT = 755,
	TBU_RBDMA_0_ERR_IRPT = 963,
	TBU_RBDMA_1_ERR_IRPT,
	TBU_RBDMA_2_ERR_IRPT,
	TBU_RBDMA_3_ERR_IRPT,
	TBU_RBDMA_4_ERR_IRPT = 932,
	TBU_RBDMA_5_ERR_IRPT,
	TBU_RBDMA_6_ERR_IRPT,
	TBU_RBDMA_7_ERR_IRPT,

	INT_ID_HDMA = 186,
};
#endif /* _CP_INTERRUPT_H_ */
