
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_AES_H
#define Z_INCLUDE_SYSCALLS_AES_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_aes_t cmrt_aes_open(uint32_t flags)
{
	return (cmrt_aes_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_OPEN);
}

static inline void cmrt_aes_close(cmrt_aes_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_CLOSE);
	return;
}

static inline int cmrt_aes_kdc_cmd(cmrt_aes_t context, cmrt_aes_operation_t operation, cmrt_aes_mode_t mode, size_t keylen, size_t taglen, cmrt_kdc_cmd_t * cmd)
{
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&operation, *(uintptr_t *)&mode, *(uintptr_t *)&keylen, *(uintptr_t *)&taglen, *(uintptr_t *)&cmd, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_KDC_CMD);
}

static inline int cmrt_aes_init(cmrt_aes_t context, cmrt_aes_operation_t operation, cmrt_aes_mode_t mode, const void * key, size_t keylen, const void * iv, size_t ivlen, size_t taglen)
{
	uintptr_t more[] = {
		*(uintptr_t *)&iv,
		*(uintptr_t *)&ivlen,
		*(uintptr_t *)&taglen
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&operation, *(uintptr_t *)&mode, *(uintptr_t *)&key, *(uintptr_t *)&keylen, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_INIT);
}

static inline int cmrt_aes_xts_set_offset(cmrt_aes_t context, uint32_t offset)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&offset, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_XTS_SET_OFFSET);
}

static inline int cmrt_aes_update(cmrt_aes_t context, const void * input, size_t inlen, void * output)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_UPDATE);
}

static inline int cmrt_aes_update_aad(cmrt_aes_t context, const void * aad, size_t aadlen)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&context, *(uintptr_t *)&aad, *(uintptr_t *)&aadlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_UPDATE_AAD);
}

static inline int cmrt_aes_final_aad(cmrt_aes_t context, const void * aad, size_t aadlen)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&context, *(uintptr_t *)&aad, *(uintptr_t *)&aadlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_FINAL_AAD);
}

static inline int cmrt_aes_final(cmrt_aes_t context, const void * input, size_t inlen, void * output)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_FINAL);
}

static inline int cmrt_aes_ae_final(cmrt_aes_t context, const void * input, size_t inlen, void * output, void * tag, size_t * taglen)
{
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, *(uintptr_t *)&tag, *(uintptr_t *)&taglen, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_AE_FINAL);
}

static inline int cmrt_aes_ccm_encode_nonce(void * buf, size_t buflen, const void * nonce, size_t noncelen, size_t ptlen, size_t taglen, int hasaad)
{
	uintptr_t more[] = {
		*(uintptr_t *)&taglen,
		*(uintptr_t *)&hasaad
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&buf, *(uintptr_t *)&buflen, *(uintptr_t *)&nonce, *(uintptr_t *)&noncelen, *(uintptr_t *)&ptlen, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_CCM_ENCODE_NONCE);
}

static inline int cmrt_aes_ccm_encode_aad(void * buf, size_t buflen, const void * aad, size_t aadlen)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&buf, *(uintptr_t *)&buflen, *(uintptr_t *)&aad, *(uintptr_t *)&aadlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_AES_CCM_ENCODE_AAD);
}


#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
