
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_CC_H
#define Z_INCLUDE_SYSCALLS_CC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_cc_t cmrt_cc_open(void)
{
	return (cmrt_cc_t) arch_syscall_invoke0(C_SYSCALL_BASE + C_SYSCALL_CMRT_CC_OPEN);
}

static inline void cmrt_cc_close(cmrt_cc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_CC_CLOSE);
}

static inline int cmrt_cc_assert(cmrt_cc_t context, uint32_t assert0, uint32_t assert1)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&context, *(uintptr_t *)&assert0, *(uintptr_t *)&assert1, C_SYSCALL_BASE + C_SYSCALL_CMRT_CC_ASSERT);
}

static inline int cmrt_cc_mix(cmrt_cc_t context, uint32_t value)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&value, C_SYSCALL_BASE + C_SYSCALL_CMRT_CC_MIX);
}

static inline int cmrt_cc_sync(cmrt_cc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_CC_SYNC);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
