
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_CCP_H
#define Z_INCLUDE_SYSCALLS_CCP_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_ccp_t cmrt_ccp_open(uint32_t flags)
{
	return (cmrt_ccp_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_OPEN);
}

static inline void cmrt_ccp_close(cmrt_ccp_t dev)
{
	arch_syscall_invoke1(*(uintptr_t *)&dev, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_CLOSE);
}

static inline int cmrt_ccp_init(cmrt_ccp_t dev, int operation, int mode, const void * key, size_t keylen, const void * iv, size_t ivlen, size_t taglen)
{
	uintptr_t more[] = {
		*(uintptr_t *)&iv,
		*(uintptr_t *)&ivlen,
		*(uintptr_t *)&taglen
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&dev, *(uintptr_t *)&operation, *(uintptr_t *)&mode, *(uintptr_t *)&key, *(uintptr_t *)&keylen, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_INIT);
}

static inline int cmrt_ccp_update(cmrt_ccp_t dev, const void * input, size_t inlen, void * output)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&dev, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_UPDATE);
}

static inline int cmrt_ccp_update_aad(cmrt_ccp_t dev, const void * aad, size_t aadlen)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&dev, *(uintptr_t *)&aad, *(uintptr_t *)&aadlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_UPDATE_AAD);
}


static inline int cmrt_ccp_final_aad(cmrt_ccp_t dev, const void * aad, size_t aadlen)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&dev, *(uintptr_t *)&aad, *(uintptr_t *)&aadlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_FINAL_AAD);
}

static inline int cmrt_ccp_final(cmrt_ccp_t dev, const void * input, unsigned int inlen, void * output)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&dev, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_FINAL);
}

static inline int cmrt_ccp_ae_final(cmrt_ccp_t dev, const void * input, size_t inlen, void * output, void * tag, size_t * taglen)
{
	return (int) arch_syscall_invoke6(*(uintptr_t *)&dev, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, *(uintptr_t *)&tag, *(uintptr_t *)&taglen, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_AE_FINAL);
}

static inline int cmrt_ccp_invalidate_key(cmrt_ccp_t dev, uint32_t flags)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&dev, *(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_CCP_INVALIDATE_KEY);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
