
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_DMAC_H
#define Z_INCLUDE_SYSCALLS_DMAC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_dmac_t cmrt_dmac_open(uint32_t flags)
{
	return (cmrt_dmac_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_DMAC_OPEN);
}

static inline void cmrt_dmac_close(cmrt_dmac_t channel)
{
	arch_syscall_invoke1(*(uintptr_t *)&channel, C_SYSCALL_BASE + C_SYSCALL_CMRT_DMAC_CLOSE);
}

static inline int cmrt_dmac_data(cmrt_dmac_t channel, uint32_t src_addr, uint32_t dst_addr, uint32_t size, cmrt_dmac_flags_t flags)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&channel, *(uintptr_t *)&src_addr, *(uintptr_t *)&dst_addr, *(uintptr_t *)&size, *(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_DMAC_DATA);
}

static inline int cmrt_dmac_fill(cmrt_dmac_t channel, uint32_t fill_data, uint32_t dst_addr, uint32_t size, cmrt_dmac_flags_t flags)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&channel, *(uintptr_t *)&fill_data, *(uintptr_t *)&dst_addr, *(uintptr_t *)&size, *(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_DMAC_FILL);
}

static inline int cmrt_dmac_sync(cmrt_dmac_t channel)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&channel, C_SYSCALL_BASE + C_SYSCALL_CMRT_DMAC_SYNC);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
