
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_FBOOT_H
#define Z_INCLUDE_SYSCALLS_FBOOT_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline int fboot_create_root(int index, const cmrt_omc_root_t * new_root)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&index, *(uintptr_t *)&new_root, C_SYSCALL_BASE + C_SYSCALL_FBOOT_CREATE_ROOT);
}

static inline int fboot_obliterate_root(int index)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&index, C_SYSCALL_BASE + C_SYSCALL_FBOOT_OBLITERATE_ROOT);
}

static inline int fboot_halt(int major, int minor)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&major, *(uintptr_t *)&minor, C_SYSCALL_BASE + C_SYSCALL_FBOOT_HALT);
}

static inline int fboot_reboot(void)
{
	return (int) arch_syscall_invoke0(C_SYSCALL_BASE + C_SYSCALL_FBOOT_REBOOT);
}

static inline int fboot_reset(uint32_t info)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&info, C_SYSCALL_BASE + C_SYSCALL_FBOOT_RESET);
}

static inline int fboot_reset_info(uint32_t * info)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&info, C_SYSCALL_BASE + C_SYSCALL_FBOOT_RESET_INFO);
}

static inline int fboot_get_image_version(enum cmrt_image_version_id image, void * version, size_t * size)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&image, *(uintptr_t *)&version, *(uintptr_t *)&size, C_SYSCALL_BASE + C_SYSCALL_FBOOT_GET_IMAGE_VERSION);
}

static inline int fboot_get_enforced_version(enum cmrt_enforced_version_id image, uint32_t * version)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&image, *(uintptr_t *)&version, C_SYSCALL_BASE + C_SYSCALL_FBOOT_GET_ENFORCED_VERSION);
}

static inline int fboot_set_enforced_version(enum cmrt_enforced_version_id image, uint32_t version)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&image, *(uintptr_t *)&version, C_SYSCALL_BASE + C_SYSCALL_FBOOT_SET_ENFORCED_VERSION);
}

static inline int fboot_data_store_read(const void * name, size_t namelen, void * data, size_t * datalen, bool user)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&name, *(uintptr_t *)&namelen, *(uintptr_t *)&data, *(uintptr_t *)&datalen, *(uintptr_t *)&user, C_SYSCALL_BASE + C_SYSCALL_FBOOT_DATA_STORE_READ);
}

static inline int fboot_data_store_write(const void * name, size_t namelen, const void * data, size_t datalen, bool user)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&name, *(uintptr_t *)&namelen, *(uintptr_t *)&data, *(uintptr_t *)&datalen, *(uintptr_t *)&user, C_SYSCALL_BASE + C_SYSCALL_FBOOT_DATA_STORE_WRITE);
}

static inline int fboot_data_store_grant(const void * name, size_t namelen, uint32_t attributes, int index, bool user)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&name, *(uintptr_t *)&namelen, *(uintptr_t *)&attributes, *(uintptr_t *)&index, *(uintptr_t *)&user, C_SYSCALL_BASE + C_SYSCALL_FBOOT_DATA_STORE_GRANT);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
