
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_FMC_H
#define Z_INCLUDE_SYSCALLS_FMC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_fmc_t cmrt_fmc_open(void)
{
	return (cmrt_fmc_t) arch_syscall_invoke0(C_SYSCALL_BASE + C_SYSCALL_CMRT_FMC_OPEN);
}

static inline void cmrt_fmc_close(cmrt_fmc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_FMC_CLOSE);
}

static inline int cmrt_fmc_read(cmrt_fmc_t context, uint32_t addr, uint32_t * data)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&context, *(uintptr_t *)&addr, *(uintptr_t *)&data, C_SYSCALL_BASE + C_SYSCALL_CMRT_FMC_READ);
}

static inline int cmrt_fmc_write(cmrt_fmc_t context, uint32_t addr, uint32_t data, uint32_t mask)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&addr, *(uintptr_t *)&data, *(uintptr_t *)&mask, C_SYSCALL_BASE + C_SYSCALL_CMRT_FMC_WRITE);
}

static inline int cmrt_fmc_set_debug_mode(cmrt_fmc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_FMC_SET_DEBUG_MODE);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
