
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_HC_H
#define Z_INCLUDE_SYSCALLS_HC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_hc_t cmrt_hc_open(const char * name, uint32_t flags)
{
	return (cmrt_hc_t) arch_syscall_invoke2(*(uintptr_t *)&name, *(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC_OPEN);
}

static inline cmrt_hc_t cmrt_cshc_open(uint32_t flags)
{
	return (cmrt_hc_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_CSHC_OPEN);
}

static inline cmrt_hc_t cmrt_whc_open(uint32_t flags)
{
	return (cmrt_hc_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_WHC_OPEN);
}

static inline cmrt_hc_t cmrt_hc2_open(uint32_t flags)
{
	return (cmrt_hc_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC2_OPEN);
}

static inline void cmrt_hc_close(cmrt_hc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC_CLOSE);
}

static inline int cmrt_hc_kdc_cmd(cmrt_hc_t context, cmrt_hash_algo_t algo, size_t keylen, cmrt_kdc_cmd_t * cmd)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&algo, *(uintptr_t *)&keylen, *(uintptr_t *)&cmd, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC_KDC_CMD);
}

static inline int cmrt_hc_init(cmrt_hc_t context, cmrt_hash_algo_t algo, const void * key, size_t keylen)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&algo, *(uintptr_t *)&key, *(uintptr_t *)&keylen, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC_INIT);
}

static inline int cmrt_hc_update(cmrt_hc_t context, const void * input, size_t inlen)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&context, *(uintptr_t *)&input, *(uintptr_t *)&inlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC_UPDATE);
}

static inline int cmrt_hc_final(cmrt_hc_t context, const void * input, size_t inlen, void * output, size_t * outlen)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&context, *(uintptr_t *)&input, *(uintptr_t *)&inlen, *(uintptr_t *)&output, *(uintptr_t *)&outlen, C_SYSCALL_BASE + C_SYSCALL_CMRT_HC_FINAL);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
