
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_KDC_H
#define Z_INCLUDE_SYSCALLS_KDC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_kdc_t cmrt_kdc_open(uint32_t flags)
{
	return (cmrt_kdc_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_KDC_OPEN);
}

static inline void cmrt_kdc_close(cmrt_kdc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_KDC_CLOSE);
}

static inline int cmrt_kdc_derive_key(cmrt_kdc_t context, cmrt_kdc_cmd_t * cmd)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&cmd, C_SYSCALL_BASE + C_SYSCALL_CMRT_KDC_DERIVE_KEY);
}

static inline int cmrt_kdc_diversify_key(cmrt_kdc_t context, cmrt_kdc_cmd_t * cmd)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&cmd, C_SYSCALL_BASE + C_SYSCALL_CMRT_KDC_DIVERSIFY_KEY);
}

static inline int cmrt_kdc_sync(cmrt_kdc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_KDC_SYNC);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
