
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_KTC_H
#define Z_INCLUDE_SYSCALLS_KTC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_ktc_t cmrt_ktc_open(uint32_t flags, uint32_t timeout)
{
	return (cmrt_ktc_t) arch_syscall_invoke2(*(uintptr_t *)&flags, *(uintptr_t *)&timeout, C_SYSCALL_BASE + C_SYSCALL_CMRT_KTC_OPEN);
}

static inline void cmrt_ktc_close(cmrt_ktc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_KTC_CLOSE);
}

static inline int cmrt_ktc_export(cmrt_ktc_t context, const cmrt_ktc_cmd_t * cmd)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&cmd, C_SYSCALL_BASE + C_SYSCALL_CMRT_KTC_EXPORT);
}

static inline int cmrt_ktc_sync(cmrt_ktc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_KTC_SYNC);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
