
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_OMC_H
#define Z_INCLUDE_SYSCALLS_OMC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_omc_t cmrt_omc_open(uint32_t flags)
{
	return (cmrt_omc_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_OMC_OPEN);
}

static inline void cmrt_omc_close(cmrt_omc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_OMC_CLOSE);
}

static inline int cmrt_omc_read(cmrt_omc_t context, uint32_t offset, void * buffer, size_t buflen)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&offset, *(uintptr_t *)&buffer, *(uintptr_t *)&buflen, C_SYSCALL_BASE + C_SYSCALL_CMRT_OMC_READ);
}

static inline int cmrt_omc_write(cmrt_omc_t context, uint32_t offset, const void * buffer, size_t buflen)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&offset, *(uintptr_t *)&buffer, *(uintptr_t *)&buflen, C_SYSCALL_BASE + C_SYSCALL_CMRT_OMC_WRITE);
}

static inline int cmrt_omc_obliterate(cmrt_omc_t context, uint32_t offset)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&offset, C_SYSCALL_BASE + C_SYSCALL_CMRT_OMC_OBLITERATE);
}

static inline int cmrt_omc_sync(cmrt_omc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_OMC_SYNC);
}

static inline int cmrt_oec_read(cmrt_omc_t context, uint32_t address, void * buffer, size_t buflen)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&address, *(uintptr_t *)&buffer, *(uintptr_t *)&buflen, C_SYSCALL_BASE + C_SYSCALL_CMRT_OEC_READ);
}

static inline int cmrt_oec_write(cmrt_omc_t context, uint32_t address, const void * buffer, size_t buflen)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&address, *(uintptr_t *)&buffer, *(uintptr_t *)&buflen, C_SYSCALL_BASE + C_SYSCALL_CMRT_OEC_WRITE);
}

static inline int cmrt_oec_commit(cmrt_omc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_OEC_COMMIT);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
