
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_PKE_H
#define Z_INCLUDE_SYSCALLS_PKE_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#include <linker/sections.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_ecc_curve_t cmrt_pke_get_curve(uint32_t curve)
{
	return (cmrt_ecc_curve_t) arch_syscall_invoke1(*(uintptr_t *)&curve, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_GET_CURVE);
}

static inline uint32_t cmrt_pke_get_curve_length(cmrt_ecc_curve_t curve)
{
	return (uint32_t) arch_syscall_invoke1(*(uintptr_t *)&curve, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_GET_CURVE_LENGTH);
}

static inline cmrt_pke_t cmrt_pke_open(uint32_t flags)
{
	return (cmrt_pke_t) arch_syscall_invoke1(*(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_OPEN);
}

static inline void cmrt_pke_close(cmrt_pke_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_CLOSE);
}

static inline int cmrt_pke_sync(cmrt_pke_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_SYNC);
}

static inline int cmrt_pke_flush(cmrt_pke_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_FLUSH);
}

static inline int cmrt_pke_ecdsa_verify(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * pub_x, const void * pub_y, const void * digest, const void * sign_r, const void * sign_s, void * rprime)
{
	uintptr_t more[] = {
		*(uintptr_t *)&sign_r,
		*(uintptr_t *)&sign_s,
		*(uintptr_t *)&rprime
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&pub_x, *(uintptr_t *)&pub_y, *(uintptr_t *)&digest, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDSA_VERIFY);
}

static inline int cmrt_pke_ecdsa_verify_hash(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * pub_x, const void * pub_y, const void * digest, unsigned int digest_len, const void * sign_r, const void * sign_s, void * rprime)
{
	uintptr_t more[] = {
		*(uintptr_t *)&digest_len,
		*(uintptr_t *)&sign_r,
		*(uintptr_t *)&sign_s,
		*(uintptr_t *)&rprime
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&pub_x, *(uintptr_t *)&pub_y, *(uintptr_t *)&digest, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDSA_VERIFY_HASH);
}

static inline int cmrt_pke_ecdsa_sign(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, const void * digest, void * sign_r, void * sign_s)
{
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&digest, *(uintptr_t *)&sign_r, *(uintptr_t *)&sign_s, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDSA_SIGN);
}

static inline int cmrt_pke_ecdsa_sign_hash(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, const void * digest, unsigned int digest_len, void * sign_r, void * sign_s)
{
	uintptr_t more[] = {
		*(uintptr_t *)&sign_r,
		*(uintptr_t *)&sign_s
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&digest, *(uintptr_t *)&digest_len, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDSA_SIGN_HASH);
}

static inline int cmrt_pke_ecdsa_keygen(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, void * pub_x, void * pub_y)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&pub_x, *(uintptr_t *)&pub_y, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDSA_KEYGEN);
}

static inline int cmrt_pke_rsa_public_key_primitive(cmrt_pke_t context, uint32_t bits, const uint8_t * mod, const uint8_t * public_key, const uint8_t * signature, uint8_t * message)
{
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&bits, *(uintptr_t *)&mod, *(uintptr_t *)&public_key, *(uintptr_t *)&signature, *(uintptr_t *)&message, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RSA_PUBLIC_KEY_PRIMITIVE);
}

static inline int cmrt_pke_rsa_sign(cmrt_pke_t context, struct cmrt_rsa_ctx * ctx)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&ctx, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RSA_SIGN);
}

static inline int cmrt_pke_rsa_key_gen(cmrt_pke_t context, struct cmrt_rsa_key * key)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&key, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RSA_KEY_GEN);
}

static inline int cmrt_pke_rsa_crt_key_gen(cmrt_pke_t context, struct cmrt_rsa_key * key)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&key, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RSA_CRT_KEY_GEN);
}

static inline int cmrt_pke_rsa_crt_sign(cmrt_pke_t context, struct cmrt_rsa_ctx * ctx)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&context, *(uintptr_t *)&ctx, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RSA_CRT_SIGN);
}

static inline int cmrt_pke_ecdh(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, const void * peer_key, void * shared_secret)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&peer_key, *(uintptr_t *)&shared_secret, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDH);
}

static inline int cmrt_pke_ecdh_keygen(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, void * pub_x)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&pub_x, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_ECDH_KEYGEN);
}

static inline int cmrt_pke_rfc7748_keygen(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, void * pub_x)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&pub_x, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RFC7748_KEYGEN);
}

static inline int cmrt_pke_rfc7748(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, const void * pub_x, void * shared_secret)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&pub_x, *(uintptr_t *)&shared_secret, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_RFC7748);
}

static inline int cmrt_pke_eddsa_sign(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, const void * message, unsigned int msglen, void * sign_r, void * sign_s)
{
	uintptr_t more[] = {
		*(uintptr_t *)&sign_r,
		*(uintptr_t *)&sign_s
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&message, *(uintptr_t *)&msglen, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_EDDSA_SIGN);
}

static inline int cmrt_pke_eddsa_verify(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * pub_x, const void * message, unsigned int msglen, const void * sign_r, const void * sign_s, void * rprime)
{
	uintptr_t more[] = {
		*(uintptr_t *)&sign_r,
		*(uintptr_t *)&sign_s,
		*(uintptr_t *)&rprime
	};
	return (int) arch_syscall_invoke6(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&pub_x, *(uintptr_t *)&message, *(uintptr_t *)&msglen, (uintptr_t) &more, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_EDDSA_VERIFY);
}

static inline int cmrt_pke_eddsa_keygen(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * priv_key, void * pub_y)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&priv_key, *(uintptr_t *)&pub_y, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_EDDSA_KEYGEN);
}

static inline int cmrt_pke_validate_ecc_xy_key(cmrt_pke_t context, cmrt_ecc_curve_t curve, const void * pub_x, const void * pub_y)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&curve, *(uintptr_t *)&pub_x, *(uintptr_t *)&pub_y, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_VALIDATE_ECC_XY_KEY);
}


static inline int cmrt_pke_ffdh(cmrt_pke_t pke, const struct cmrt_ffdh_param * param, const uint8_t * priv_key, const uint8_t * peer_key, uint8_t * pub_key, uint8_t * shared_key)
{
	return (int) arch_syscall_invoke6(*(uintptr_t *)&pke, *(uintptr_t *)&param, *(uintptr_t *)&priv_key, *(uintptr_t *)&peer_key, *(uintptr_t *)&pub_key, *(uintptr_t *)&shared_key, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_FFDH);
}

static inline int cmrt_pke_ffdh_private_keygen(cmrt_pke_t context, size_t mod_size, const uint8_t * q, uint8_t * priv_key)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&mod_size, *(uintptr_t *)&q, *(uintptr_t *)&priv_key, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_FFDH_PRIVATE_KEYGEN);
}

static inline int cmrt_pke_ffdh_verify(cmrt_pke_t pke, const struct cmrt_ffdh_param * param)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&pke, *(uintptr_t *)&param, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_FFDH_VERIFY);
}

static inline int cmrt_pke_ffdh_parmgen(cmrt_pke_t pke, size_t pbits, size_t qbits, struct cmrt_ffdh_param * param)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&pke, *(uintptr_t *)&pbits, *(uintptr_t *)&qbits, *(uintptr_t *)&param, C_SYSCALL_BASE + C_SYSCALL_CMRT_PKE_FFDH_PARMGEN);
}


#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
