
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_SAC_H
#define Z_INCLUDE_SYSCALLS_SAC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline uint32_t cmrt_sac_read32(uintptr_t addr)
{
	return (uint32_t)arch_syscall_invoke1(*(uintptr_t *)&addr, C_SYSCALL_BASE +
										  C_SYSCALL_CMRT_SAC_READ32);
}

static inline void cmrt_sac_write32(uint32_t data, uintptr_t addr)
{
	arch_syscall_invoke2(*(uintptr_t *)&data, *(uintptr_t *)&addr, C_SYSCALL_BASE +
						 C_SYSCALL_CMRT_SAC_WRITE32);
}

static inline void * cmrt_sac_memcpy(void * dst, const void * src, size_t num)
{
	return (void *)arch_syscall_invoke3(*(uintptr_t *)&dst, *(uintptr_t *)&src, *(uintptr_t *)&num,
										C_SYSCALL_BASE + C_SYSCALL_CMRT_SAC_MEMCPY);
}

static inline uint8_t cmrt_sac_read8(uintptr_t addr)
{
	return (uint8_t)arch_syscall_invoke4(*(uintptr_t *)&addr, C_SYSCALL_BASE +
										 C_SYSCALL_CMRT_SAC_READ8);
}

static inline void cmrt_sac_write8(uint8_t data, uintptr_t addr)
{
	arch_syscall_invoke5(*(uintptr_t *)&data, *(uintptr_t *)&addr, C_SYSCALL_BASE +
						 C_SYSCALL_CMRT_SAC_WRITE8);
}
#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
