
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_SIC_H
#define Z_INCLUDE_SYSCALLS_SIC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_sic_t cmrt_sic_open(uint32_t flags, uint32_t flowid)
{
	return (cmrt_sic_t) arch_syscall_invoke2(*(uintptr_t *)&flags, *(uintptr_t *)&flowid, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_OPEN);
}

static inline void cmrt_sic_close(cmrt_sic_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_CLOSE);
}

    static inline int cmrt_sic_read(cmrt_sic_t context, void * buffer, size_t * buflen, uint32_t * peerid, uint32_t flags)
{
	return (int) arch_syscall_invoke5(*(uintptr_t *)&context, *(uintptr_t *)&buffer, *(uintptr_t *)&buflen, *(uintptr_t *)&peerid, *(uintptr_t *)&flags, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_READ);
}

static inline int cmrt_sic_write(cmrt_sic_t context, const void * buffer, size_t buflen, uint32_t peerid)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&buffer, *(uintptr_t *)&buflen, *(uintptr_t *)&peerid, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_WRITE);
}

static inline int cmrt_sic_sync(cmrt_sic_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_SYNC);
}

static inline uint32_t cmrt_sic_read_reg(uint32_t reg)
{
	return (uint32_t) arch_syscall_invoke1(*(uintptr_t *)&reg, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_READ_REG);
}

static inline void cmrt_sic_write_reg(uint32_t reg, uint32_t value)
{
	arch_syscall_invoke2(*(uintptr_t *)&reg, *(uintptr_t *)&value, C_SYSCALL_BASE + C_SYSCALL_CMRT_SIC_WRITE_REG);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
