
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_SID_H
#define Z_INCLUDE_SYSCALLS_SID_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_sid_t cmrt_sid_open(uint32_t flags, uint32_t irqs)
{
	return (cmrt_sid_t) arch_syscall_invoke2(*(uintptr_t *)&flags, *(uintptr_t *)&irqs, C_SYSCALL_BASE + C_SYSCALL_CMRT_SID_OPEN);
}

static inline void cmrt_sid_close(cmrt_sid_t dev)
{
	arch_syscall_invoke1(*(uintptr_t *)&dev, C_SYSCALL_BASE + C_SYSCALL_CMRT_SID_CLOSE);
}

static inline int cmrt_sid_watch(cmrt_sid_t dev, uint32_t watch, uint32_t * irqs)
{
	return (int) arch_syscall_invoke3(*(uintptr_t *)&dev, *(uintptr_t *)&watch, *(uintptr_t *)&irqs, C_SYSCALL_BASE + C_SYSCALL_CMRT_SID_WATCH);
}

static inline int cmrt_sid_sync(cmrt_sid_t dev)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&dev, C_SYSCALL_BASE + C_SYSCALL_CMRT_SID_SYNC);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
