
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_TMC_H
#define Z_INCLUDE_SYSCALLS_TMC_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline cmrt_tmc_t cmrt_tmc_open(uint32_t flags, void *arg)
{
    return (cmrt_tmc_t) arch_syscall_invoke2(*(uintptr_t *)&flags, *(uintptr_t *)&arg, C_SYSCALL_BASE + C_SYSCALL_CMRT_TMC_OPEN);
}

static inline void cmrt_tmc_close(cmrt_tmc_t context)
{
	arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_TMC_CLOSE);
}

static inline int cmrt_tmc_command(cmrt_tmc_t context, cmrt_tmc_command_t command, void * buffer, size_t size)
{
	return (int) arch_syscall_invoke4(*(uintptr_t *)&context, *(uintptr_t *)&command, *(uintptr_t *)&buffer, *(uintptr_t *)&size, C_SYSCALL_BASE + C_SYSCALL_CMRT_TMC_COMMAND);
}

static inline int cmrt_tmc_sync(cmrt_tmc_t context)
{
	return (int) arch_syscall_invoke1(*(uintptr_t *)&context, C_SYSCALL_BASE + C_SYSCALL_CMRT_TMC_SYNC);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
