
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef Z_INCLUDE_SYSCALLS_UTIL_H
#define Z_INCLUDE_SYSCALLS_UTIL_H


#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#include <linker/sections.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

static inline int cmrt_get_random(void * buf, size_t len)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&buf, *(uintptr_t *)&len, C_SYSCALL_BASE + C_SYSCALL_CMRT_GET_RANDOM);
}

static inline int cmrt_get_entropy(void * buf, size_t len)
{
	return (int) arch_syscall_invoke2(*(uintptr_t *)&buf, *(uintptr_t *)&len, C_SYSCALL_BASE + C_SYSCALL_CMRT_GET_ENTROPY);
}

static inline void cmrt_init_tmc_config(cmrt_tmc_init_params_t * params)
{
	arch_syscall_invoke1(*(uintptr_t *)&params, C_SYSCALL_BASE + C_SYSCALL_CMRT_INIT_TMC_CONFIG);
}

static inline uint64_t cmrt_perf_ref(void)
{
	uint64_t ret64;
	(void)arch_syscall_invoke1((uintptr_t)&ret64, C_SYSCALL_BASE + C_SYSCALL_CMRT_PERF_REF);
	return ret64;
}

static inline uint64_t cmrt_uptime_get(void)
{
	uint64_t ret64;
	(void)arch_syscall_invoke1((uintptr_t)&ret64, C_SYSCALL_BASE + C_SYSCALL_CMRT_UPTIME_GET);
	return ret64;
}

static inline uint32_t cmrt_access(uint32_t flags, const void *pbuf, size_t nbuf)
{
	return (uint32_t)arch_syscall_invoke3(*(uintptr_t *)&flags, *(uintptr_t *)&pbuf, *(uintptr_t *)&nbuf, C_SYSCALL_BASE + C_SYSCALL_CMRT_ACCESS);
}

static inline void cmrt_exit_container(int value)
{
	(void)arch_syscall_invoke1(value, C_SYSCALL_BASE + C_SYSCALL_CMRT_EXIT_CONTAINER);
}

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
