/*
 * Copyright (c) 2021-2023 Cryptography Research, Inc. (CRI).
 * A license or authorization from CRI is needed to use this file.
 */

#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <assert.h>
#include <ctype.h>
#include <sys/types.h>
#include <stdalign.h>
#include <stdbool.h>

#include <container.h>
#include <logging/log.h>
#include <drivers/cmrt/cmrt.h>
#include <drivers/cmrt/sic.h>
#include <cmrt/ucu/ecies.h>

#define BUFSZ 4096
#define MAX_HASH_SIZE 64

#define MATCH(argp, argl, lstr) \
	((argl == sizeof(lstr)-1) && (memcmp(argp, lstr, sizeof(lstr)-1) == 0))

/* Global buffer for receive and response messages from SIC. */
alignas(4) uint8_t buffer[BUFSZ];
alignas(4) uint8_t buffer_tmp[BUFSZ];

cmrt_ecies_t ecies = CMRT_INVALID_HANDLE;


static void print_usage(void)
{
	LOG_INF("COMMAND:  open|close|init|update|final\n");

	LOG_INF("open USE_HC2  open the ecies context/core");
	LOG_INF("USE_HC2:      boolean (0 or 1), use HC2 or not\n");

	LOG_INF("close         close the ecies context/core\n");

	LOG_INF("init OP MODE PEERX PRIV");
	LOG_INF("OP:     encrypt|decrypt");
	LOG_INF("MODE:   int, ECIES mode. See cmrt_ecies_init api doc");
	LOG_INF("PEERX:  for encrypt, the recipient's pubkey, for decrypt,");
	LOG_INF("        the message pubkey, generated by the encrypt init");
	LOG_INF("PRIV:   (decrypt only) ECIES private key\n");

	LOG_INF("update DATA");
	LOG_INF("DATA:   data to encrypt/decrypt, length multiple of 16");
	LOG_INF("        You can perform 0 or more of this operation\n");

	LOG_INF("final TAGLEN DATA SHARED_INFO");
	LOG_INF("DATA:   last block of data to encrypt/decrypt");
	LOG_INF("        No length requirement\n");
}

/* Converts a (decimal) string into a uint32_t. Returns the parsed number.
 * Processes exactly `sl` bytes from the string `s`.
 * On conversion error sets errno to -EINVAL and returns 0.
 *
 * Encountering a nullbyte is a a conversion error.
 * An empty string (`sl`== 0) is a conversion error.
 * No wrapparound checks on the parsed number or on `sl`.
 * */
static uint32_t conv_strl2u32(const char *s, size_t sl)
{
	uint32_t acc = 0;
	const char *s_end = s + sl; /* no ovf check */
	for (; (size_t)s < (size_t)s_end; ++s) {
		char v = *s;
		if (v < '0' || v > '9') {
			errno = EINVAL;
			return 0;
		}
		v -= '0';
		acc *= 10; /* no ovf check */
		acc += v;
	}
	return acc;
}

static void debug_print_blob(uint8_t *blob, size_t sz, const char *info_text)
{
#ifdef CONFIG_DEBUG
#define _MAX_DBG_LEN 64
	if (!blob || !sz) return;

	size_t sz_hex = sz*2;
	uint8_t blob_hex[_MAX_DBG_LEN*2];
	size_t written = bin2hex(blob, MIN(sz, _MAX_DBG_LEN), (char*)blob_hex, _MAX_DBG_LEN*2);

	LOG_DBG("%s%.*s%s", info_text, (int)sz_hex, blob_hex,
		(written < sz_hex) ? "..." /*cropped*/ : "" );
#undef _MAX_DBG_LEN
#else
	(void)blob; (void)sz; (void)info_text;
#endif
}

static void ecies_close(void) {
	if (cmrt_is_valid(ecies)) {
		LOG_INF("Closing ECIES context");
		cmrt_ecies_close(ecies);

		ecies = CMRT_INVALID_HANDLE;
	}
}

/*
 * yet to find a home...
 */
static inline uint32_t argl_init(uint8_t **argpp)
{
	const uint32_t argl = **(uint32_t**)argpp;
	*argpp += sizeof(uint32_t);
	return argl;
}

static inline uint32_t argl_next(uint8_t **argpp, uint32_t argl)
{
	*argpp += ((argl + 3) & ~3);
	argl = **(uint32_t**)argpp;
	*argpp += sizeof(uint32_t);
	return argl;
}

static bool is_valid_ecies_mode(uint32_t v)
{
	/* XXX: Relies on enum cmrt_ecies_mode_e in libucu
	 * header not changing. */
	if (v > CMRT_ECIES_P521_KDF1_SHA3_512_AES256_HMAC_SHA3_512) {
		return false;
	}

	return true;
}

static int process_init(uint8_t *argp, uint32_t argc, size_t *_buflen)
{
	int rc = -1;

	if (argc != 4) {
		LOG_ERR("%s: invalid number of args", __func__);
		goto err;
	}

	if (!cmrt_is_valid(ecies)) {
		LOG_ERR("%s: ECIES not open", __func__);
		goto err;
	}

	/* OP */
	cmrt_ecies_operation_t op;
	uint32_t argl = argl_init(&argp);
	if (MATCH(argp, argl, "encrypt")) {
		op = CMRT_ECIES_ENCRYPT;
		LOG_DBG("%s: op=CMRT_ECIES_ENCRYPT", __func__);
	} else if (MATCH(argp, argl, "decrypt")) {
		op = CMRT_ECIES_DECRYPT;
		LOG_DBG("%s: op=CMRT_ECIES_DECRYPT", __func__);
	} else {
		LOG_ERR("%s: invalid operation", __func__);
		goto err;
	}

	/* MODE */
	argl = argl_next(&argp, argl);
	errno = 0;
	uint32_t _mode = conv_strl2u32((char *)argp, argl);
	if (errno || !is_valid_ecies_mode(_mode)) {
		LOG_ERR("%s: invalid mode (%lu)", __func__, _mode);
		goto err;
	}
	cmrt_ecies_mode_t mode = (cmrt_ecies_mode_t)_mode;
	LOG_DBG("%s: mode=%lu", __func__, _mode);

	/* PEERX (for encrypt op, this is the recipient's pubkey,
	 * for decrypt op, this is the ciphertext's pubkey,
	 * which is the output of init(encrypt)) */
	uint32_t peerx_len = argl = argl_next(&argp, argl);
	uint8_t *peerx = argp;
	LOG_DBG("%s: peerx_len=%lu", __func__, peerx_len);
	debug_print_blob(peerx, peerx_len, "init: peerx: 0x");

	/* PRIV */
	size_t privlen = argl = argl_next(&argp, argl);
	uint8_t *priv = argp;
	LOG_DBG("%s: privlen=%u", __func__, privlen);
	debug_print_blob(priv, privlen, "init: priv: 0x");
	if (!privlen) { priv = NULL; }

	/* for an encrypt op we can't  give a privkey. */
	if (op == CMRT_ECIES_ENCRYPT && (priv || privlen)) {
		LOG_ERR("%s: error, provided privkey for encrypt op", __func__);
		goto err;
	}

	/* for a decrypt op, the privkey must not be empty. */
	if (op == CMRT_ECIES_DECRYPT && (!priv || !privlen)) {
		LOG_ERR("%s: error, missing privkey for decrypt op", __func__);
		goto err;
	}

	alignas(4) uint8_t out_pubx[128]; // XXX
	rc = cmrt_ecies_init(ecies, mode, op, priv, privlen, peerx, peerx_len,
		out_pubx, peerx_len);

	if (rc != 0) {
		LOG_ERR("%s: cmrt_ecies_init failed with %d", __func__, rc);
		goto err;
	}

	memcpy(buffer, out_pubx, peerx_len);
	*_buflen = peerx_len;

	return 0;

err:
	ecies_close();
	return rc;
}

static int process_update(uint8_t *argp, uint32_t argc, size_t *_buflen)
{
	int rc = -1;

	if (argc != 1) {
		LOG_ERR("%s: invalid number of args", __func__);
		goto err;
	}

	if (!cmrt_is_valid(ecies)) {
		LOG_ERR("%s: ECIES not open", __func__);
		goto err;
	}

	uint32_t argl = argl_init(&argp);

	if ((argl & 15) != 0) {
		LOG_ERR("got update not multiple of 16");
		goto err;
	}

	LOG_DBG("performing cmrt_ecies_update with inlen=%lu", argl);
	rc = cmrt_ecies_update(ecies, argp, (size_t)argl, buffer_tmp);
	if (rc != 0) {
		LOG_ERR("cmrt_ecies_update failed with %d", rc);
		goto err;
	}
	memcpy(buffer, buffer_tmp, argl);
	*_buflen = argl;

	return 0;
err:
	ecies_close();
	return rc;
}

static int process_final(uint8_t *argp, uint32_t argc, size_t *_buflen)
{
	int rc = -1;

	if (argc != 3) {
		LOG_ERR("%s: invalid number of args", __func__);
		goto err;
	}

	if (!cmrt_is_valid(ecies)) {
		LOG_ERR("%s: ECIES not open", __func__);
		goto err;
	}

	/* TAGLEN */
	uint32_t argl = argl_init(&argp);
	errno = 0;
	size_t taglen = conv_strl2u32((char *)argp, argl);
	LOG_DBG("%s: taglen=%u", __func__, taglen);
	if (errno || taglen > MAX_HASH_SIZE) {
		LOG_ERR("%s: invalid taglen", __func__);
		goto err;
	}

	/* DATA */
	/* NOTE: if input data length is not multiple of AES_BLOCK_BYTES (16),
	 * the last block will be cropped. */
	size_t inlen = argl = argl_next(&argp, argl);
	uint8_t *in = argp;
	if (!inlen) { in = NULL; }
	LOG_DBG("%s: inlen=%zu", __func__, inlen);
	debug_print_blob(in, inlen, "final: in: 0x");

	/* SHARED_INFO */
	size_t shared_info_len = argl = argl_next(&argp, argl);
	uint8_t *shared_info = argp;
	if (!shared_info_len) { shared_info = NULL; }
	LOG_DBG("%s: shared_info_len=%zu", __func__, shared_info_len);
	debug_print_blob(shared_info, shared_info_len, "final: shared_info: 0x");

	LOG_DBG("performing cmrt_ecies_final with inlen=%u", inlen);
	alignas(4) uint8_t out_tag[MAX_HASH_SIZE] = {0};
	rc = cmrt_ecies_final(ecies, in, inlen, shared_info, shared_info_len,
		buffer_tmp, out_tag, taglen);
	if (rc != 0) {
		LOG_ERR("cmrt_ecies_final failed with %d", rc);
		goto err;
	}

	*_buflen = 0;
	if (taglen) {
		memcpy(buffer, out_tag, taglen);
		*_buflen += taglen;
	}

	memcpy(buffer+taglen, buffer_tmp, inlen);
	*_buflen += inlen;

	return 0;
err:
	ecies_close();
	return rc;
}

static int process_open(uint8_t *argp, uint32_t argc, size_t *_buflen)
{
	(void) _buflen;

	if (argc != 1) {
		LOG_ERR("%s: invalid number of args", __func__);
		return -1;
	}

	/* USE_HC2 */
	uint32_t argl = argl_init(&argp);
	errno = 0;
	int use_hc2 = (int)conv_strl2u32((char *)argp, argl);
	if (errno) {
		LOG_ERR("%s: invalid use_hc2", __func__);
		return -1;
	}
	use_hc2 = !!use_hc2;
	LOG_DBG("%s: use_hc2=%d", __func__, use_hc2);

	if (cmrt_is_valid(ecies)) {
		LOG_ERR("%s: ECIES alr eady open", __func__);
		return -1;
	}

	ecies = cmrt_ecies_open(use_hc2 ? CMRT_ECIES_O_USE_HC2 : 0);
	if (!cmrt_is_valid(ecies)) {
		LOG_ERR("%s: Cannot open ECIES", __func__);
		return -1;
	}

	return 0;
}

static int process_close(uint8_t *argp, uint32_t argc, size_t *_buflen)
{
	(void) _buflen;
	(void) argp;
	(void) argc;

	if (!cmrt_is_valid(ecies)) {
		LOG_ERR("%s: ECIES is already closed", __func__);
		return -1;
	}

	ecies_close();
	ecies = CMRT_INVALID_HANDLE;

	return 0;
}

static int process_message(uint8_t *buffer, size_t *_buflen)
{
	uint8_t *argp = buffer;
	uint32_t argc = argl_init(&argp);
	/*
	 * Check argument array length matches message length, then
	 * commands can trust the lengths of inputs given to them.
	 */
	const uint8_t *ap2 = argp;
	for (size_t i = 0; i < argc; i++) {
		const int alen = *(uint32_t*)ap2;
		const uint8_t *const nap = ap2 + ((alen + 7) & ~3);
		if (nap < ap2 || (size_t)(nap - buffer) > *_buflen) {
			LOG_ERR("Message format error: args length mismatch");
			return -EINVAL;
		}
		ap2 = nap;
	}
	*_buflen = 0;
	uint32_t argl = argl_init(&argp);
	uint8_t *argp_next = argp + ((argl + 3) & ~3); /* revisit how to do .*/
	argc--;

	/* dispatch OPERATION */

	if (MATCH(argp, argl, "open")) {
		return process_open(argp_next, argc, _buflen);
	}
	if (MATCH(argp, argl, "close")) {
		return process_close(argp_next, argc, _buflen);
	}
	if (MATCH(argp, argl, "init")) {
		return process_init(argp_next, argc, _buflen);
	}
	if (MATCH(argp, argl, "update")) {
		return process_update(argp_next, argc, _buflen);
	}
	if (MATCH(argp, argl, "final")) {
		return process_final(argp_next, argc, _buflen);
	}

	/* else */
	argp[argl] = '\0';
	LOG_ERR("%s: Invalid COMMAND", argp);
	return 0;
}

static int main_loop(uint32_t flowid)
{
	cmrt_sic_t sic = cmrt_sic_open(CMRT_O_SYNC, flowid);
	if (!cmrt_is_valid(sic)) {
		LOG_INF("Cannot open SIC");
		return -ENODEV;
	}
	LOG_INF("Waiting for SIC input on flow 0x%x...", (unsigned int)flowid);

	int res = 0;
	while (true) {
		uint32_t peerid;
		size_t buflen = sizeof(buffer) - 4;
		/* memset(buffer, 0, sizeof(buffer)); */
		res = cmrt_sic_read(sic, buffer, &buflen, &peerid, 0);
		if (res < 0) {
			LOG_INF("Failed to read from HLOS: %d!", res);
			break;
		}

		LOG_INF("Got request from HLOS of %zu bytes", buflen);
		if (buflen)
			LOG_HEXDUMP_DBG(buffer, MIN(64, buflen), "Request from HLOS:");

		/* Processing failure is a fatal error. */
		res = process_message(buffer, &buflen);
		if (res < 0) {
			LOG_INF("Failed to process the message: %d!", res);
			break;
		}

		/* The same buffer holds the response to HLOS. */
		LOG_INF("Sending response to HLOS of %zu bytes", buflen);
		if (buflen)
			LOG_HEXDUMP_DBG(buffer, MIN(64, buflen), "Response to HLOS:");

		if (!buflen) continue;
		res = cmrt_sic_write(sic, buffer, buflen, peerid);
		if (res < 0) {
			LOG_INF("Failed to write to HLOS: %d!", res);
			break;
		}
	}
	cmrt_sic_close(sic);
	ecies_close();
	return res;
}

void container(void *p1, void *p2, void *p3)
{
	(void)p2;
	(void)p3;
	print_usage();
	int res = main_loop((uint32_t)p1);
	LOG_ERR("Container main_loop exited with %d!", res);
}
