CTOOLDIR=../common

user_name = libucu.a
user_objs = ./src/ecies.o \
            ./src/endianness.o \
            ./src/reverse.o \
            ./src/rsa_pad.o \
            ./src/kdf.o \
            src/bitstat.o \
            src/edges.o

include ../../common/lib.mk
