/*
 * Copyright 2024 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * PROPRIETARY/CONFIDENTIAL
 *
 * This software is the confidential and proprietary information of
 * Samsung Electronics Co., Ltd. ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only
 * in accordance with the terms of the license agreement you entered into with
 * Samsung Electronics Co., Ltd. ("SAMSUNG").
 *
 * SAMSUNG MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
 * NON-INFRINGEMENT. SAMSUNG SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY
 * LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR
 * ITS DERIVATIVES.
 *
 */
#pragma once

#include <stdint.h>

#define NUM_OF_CHIPS (4)
#define NUM_OF_ACTIVE_RBC (4)

#define BLK_RBC_V00_BASE		(0x1FF5000000ULL)
#define BLK_RBC_V01_BASE		(0x1FF5400000ULL)
#define BLK_RBC_V10_BASE		(0x1FF5800000ULL)
#define BLK_RBC_V11_BASE		(0x1FF5C00000ULL)
#define BLK_RBC_H00_BASE		(0x1FF6000000ULL)
#define BLK_RBC_H01_BASE		(0x1FF6400000ULL)

#define BLK_RBC_LINK_STAT	(0x40014ULL)
#define BLK_RBC_LINK_CAP	(0x4000CULL)
#define BLK_RBC_SCRATCH3	(0x4E040ULL)

#if EVT_VER == 0
    #define BLK_RBC_CRC_LOG		(0x4995CULL)
#else
    #define BLK_RBC_CRC_LOG		(0x4915CULL)
#endif

#define BLK_RBC_V00_LINK_STAT (BLK_RBC_V00_BASE + BLK_RBC_LINK_STAT)
#define BLK_RBC_V01_LINK_STAT (BLK_RBC_V01_BASE + BLK_RBC_LINK_STAT)
#define BLK_RBC_V10_LINK_STAT (BLK_RBC_V10_BASE + BLK_RBC_LINK_STAT)
#define BLK_RBC_V11_LINK_STAT (BLK_RBC_V11_BASE + BLK_RBC_LINK_STAT)
#define BLK_RBC_H00_LINK_STAT (BLK_RBC_H00_BASE + BLK_RBC_LINK_STAT)
#define BLK_RBC_H01_LINK_STAT (BLK_RBC_H01_BASE + BLK_RBC_LINK_STAT)

#define BLK_RBC_V00_LINK_CAP (BLK_RBC_V00_BASE + BLK_RBC_LINK_CAP)
#define BLK_RBC_V01_LINK_CAP (BLK_RBC_V01_BASE + BLK_RBC_LINK_CAP)
#define BLK_RBC_V10_LINK_CAP (BLK_RBC_V10_BASE + BLK_RBC_LINK_CAP)
#define BLK_RBC_V11_LINK_CAP (BLK_RBC_V11_BASE + BLK_RBC_LINK_CAP)
#define BLK_RBC_H00_LINK_CAP (BLK_RBC_H00_BASE + BLK_RBC_LINK_CAP)
#define BLK_RBC_H01_LINK_CAP (BLK_RBC_H01_BASE + BLK_RBC_LINK_CAP)

#define BLK_RBC_V00_CRC_LOG (BLK_RBC_V00_BASE + BLK_RBC_CRC_LOG)
#define BLK_RBC_V01_CRC_LOG (BLK_RBC_V01_BASE + BLK_RBC_CRC_LOG)
#define BLK_RBC_V10_CRC_LOG (BLK_RBC_V10_BASE + BLK_RBC_CRC_LOG)
#define BLK_RBC_V11_CRC_LOG (BLK_RBC_V11_BASE + BLK_RBC_CRC_LOG)
#define BLK_RBC_H00_CRC_LOG (BLK_RBC_H00_BASE + BLK_RBC_CRC_LOG)
#define BLK_RBC_H01_CRC_LOG (BLK_RBC_H01_BASE + BLK_RBC_CRC_LOG)

#define BLK_RBC_V00_SCRATCH3 (BLK_RBC_V00_BASE + BLK_RBC_SCRATCH3)
#define BLK_RBC_V01_SCRATCH3 (BLK_RBC_V01_BASE + BLK_RBC_SCRATCH3)
#define BLK_RBC_V10_SCRATCH3 (BLK_RBC_V10_BASE + BLK_RBC_SCRATCH3)
#define BLK_RBC_V11_SCRATCH3 (BLK_RBC_V11_BASE + BLK_RBC_SCRATCH3)
#define BLK_RBC_H00_SCRATCH3 (BLK_RBC_H00_BASE + BLK_RBC_SCRATCH3)
#define BLK_RBC_H01_SCRATCH3 (BLK_RBC_H01_BASE + BLK_RBC_SCRATCH3)

extern const uint64_t crc_err_count_base[NUM_OF_CHIPS][NUM_OF_ACTIVE_RBC];
extern const uint64_t link_stat_base_addr[NUM_OF_CHIPS][NUM_OF_ACTIVE_RBC];
extern const uint64_t link_cap_base_addr[NUM_OF_CHIPS][NUM_OF_ACTIVE_RBC];

void _check_ucie_link_speed(void);
void show_crc_err_count(void);
uint64_t get_crc_err_cnt(uint64_t crc_err_cnt_count[][4]);
