user_footer = footer.json
user_name = sample_edwards_curve
user_libs = -lcmrt_v1 -los -lc
user_includes =
user_objs = sample_edwards_curve.o
user_cflags = -Wno-format -Wno-incompatible-pointer-types
user_ldflags =

include ../../../common/container.mk
