CTOOLDIR=../common

user_name = libcaliptra.a
user_objs = \
  ./src/x509.o \
  ./src/crypto.o \
  ./src/zeroize.o \
  ./src/assets.o \
  ./src/uds.o \
  ./src/field_entropy.o \
  ./src/flow.o \
  ./src/handover.o

include ../../common/lib.mk
