#!/usr/bin/env python3
#
# Copyright (c) 2017 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

"""
Script to generate system call invocation macros

This script parses the system call metadata JSON file emitted by
parse_syscalls.py to create several files:

- A file containing weak aliases of any potentially unimplemented system calls,
  as well as the system call dispatch table, which maps system call type IDs
  to their handler functions.

- A header file defining the system call type IDs, as well as function
  prototypes for all system call handler functions.

- A directory containing header files. Each header corresponds to a header
  that was identified as containing system call declarations. These
  generated headers contain the inline invocation functions for each system
  call in that header.
"""

import sys
import re
import argparse
import os
import json

types64 = ["int64_t", "uint64_t"]

# The kernel linkage is complicated.  These functions from
# userspace_handlers.c are present in the kernel .a library after
# userspace.c, which contains the weak fallbacks defined here.  So the
# linker finds the weak one first and stops searching, and thus won't
# see the real implementation which should override.  Yet changing the
# order runs afoul of a comment in CMakeLists.txt that the order is
# critical.  These are core syscalls that won't ever be unconfigured,
# just disable the fallback mechanism as a simple workaround.
noweak = ["z_mrsh_k_object_release",
          "z_mrsh_k_object_access_grant",
          "z_mrsh_k_object_alloc"]

table_template = """/* auto-generated by gen_syscalls.py, don't edit */

/* Weak handler functions that get replaced by the real ones unless a system
 * call is not implemented due to kernel configuration.
 */
%s

const _k_syscall_handler_t _k_syscall_table[K_SYSCALL_LIMIT] = {
\t%s
};
"""

# Fixed CMRT user container syscall table. This could be generated
# from a file but let's make it easy for now...
table_container = """
const _k_syscall_handler_t _c_syscall_table[C_SYSCALL_LIMIT] = {
        [C_SYSCALL_CMRT_AES_OPEN] = z_mrsh_cmrt_aes_open,
        [C_SYSCALL_CMRT_AES_CLOSE] = z_mrsh_cmrt_aes_close,
        [C_SYSCALL_CMRT_AES_KDC_CMD] = z_mrsh_cmrt_aes_kdc_cmd,
        [C_SYSCALL_CMRT_AES_INIT] = z_mrsh_cmrt_aes_init,
        [C_SYSCALL_CMRT_AES_XTS_SET_OFFSET] = z_mrsh_cmrt_aes_xts_set_offset,
        [C_SYSCALL_CMRT_AES_UPDATE] = z_mrsh_cmrt_aes_update,
        [C_SYSCALL_CMRT_AES_UPDATE_AAD] = z_mrsh_cmrt_aes_update_aad,
        [C_SYSCALL_CMRT_AES_FINAL_AAD] = z_mrsh_cmrt_aes_final_aad,
        [C_SYSCALL_CMRT_AES_FINAL] = z_mrsh_cmrt_aes_final,
        [C_SYSCALL_CMRT_AES_AE_FINAL] = z_mrsh_cmrt_aes_ae_final,
        [C_SYSCALL_CMRT_CC_OPEN] = z_mrsh_cmrt_cc_open,
        [C_SYSCALL_CMRT_CC_CLOSE] = z_mrsh_cmrt_cc_close,
        [C_SYSCALL_CMRT_CC_ASSERT] = z_mrsh_cmrt_cc_assert,
        [C_SYSCALL_CMRT_CC_MIX] = z_mrsh_cmrt_cc_mix,
        [C_SYSCALL_CMRT_CC_SYNC] = z_mrsh_cmrt_cc_sync,
        [C_SYSCALL_CMRT_CCP_OPEN] = z_mrsh_cmrt_ccp_open,
        [C_SYSCALL_CMRT_CCP_CLOSE] = z_mrsh_cmrt_ccp_close,
        [C_SYSCALL_CMRT_CCP_INIT] = z_mrsh_cmrt_ccp_init,
        [C_SYSCALL_CMRT_CCP_UPDATE] = z_mrsh_cmrt_ccp_update,
        [C_SYSCALL_CMRT_CCP_UPDATE_AAD] = z_mrsh_cmrt_ccp_update_aad,
        [C_SYSCALL_CMRT_CCP_FINAL_AAD] = z_mrsh_cmrt_ccp_final_aad,
        [C_SYSCALL_CMRT_CCP_FINAL] = z_mrsh_cmrt_ccp_final,
        [C_SYSCALL_CMRT_CCP_AE_FINAL] = z_mrsh_cmrt_ccp_ae_final,
        [C_SYSCALL_CMRT_CCP_INVALIDATE_KEY] = z_mrsh_cmrt_ccp_invalidate_key,
        [C_SYSCALL_CMRT_WAIT] = z_mrsh_cmrt_wait,
        [C_SYSCALL_CMRT_DMAC_OPEN] = z_mrsh_cmrt_dmac_open,
        [C_SYSCALL_CMRT_DMAC_CLOSE] = z_mrsh_cmrt_dmac_close,
        [C_SYSCALL_CMRT_DMAC_DATA] = z_mrsh_cmrt_dmac_data,
        [C_SYSCALL_CMRT_DMAC_FILL] = z_mrsh_cmrt_dmac_fill,
        [C_SYSCALL_CMRT_DMAC_SYNC] = z_mrsh_cmrt_dmac_sync,
        [C_SYSCALL_CMRT_FMC_OPEN] = z_mrsh_cmrt_fmc_open,
        [C_SYSCALL_CMRT_FMC_CLOSE] = z_mrsh_cmrt_fmc_close,
        [C_SYSCALL_CMRT_FMC_READ] = z_mrsh_cmrt_fmc_read,
        [C_SYSCALL_CMRT_FMC_WRITE] = z_mrsh_cmrt_fmc_write,
        [C_SYSCALL_CMRT_FMC_GPIO_READ] = handler_no_syscall,
        [C_SYSCALL_CMRT_FMC_GPIO_WRITE] = handler_no_syscall,
        [C_SYSCALL_CMRT_FMC_SET_DEBUG_MODE] = z_mrsh_cmrt_fmc_set_debug_mode,
        [C_SYSCALL_CMRT_HC_OPEN] = z_mrsh_cmrt_hc_open,
        [C_SYSCALL_CMRT_HC_CLOSE] = z_mrsh_cmrt_hc_close,
        [C_SYSCALL_CMRT_HC_KDC_CMD] = z_mrsh_cmrt_hc_kdc_cmd,
        [C_SYSCALL_CMRT_HC_INIT] = z_mrsh_cmrt_hc_init,
        [C_SYSCALL_CMRT_HC_UPDATE] = z_mrsh_cmrt_hc_update,
        [C_SYSCALL_CMRT_HC_FINAL] = z_mrsh_cmrt_hc_final,
        [C_SYSCALL_CMRT_KDC_OPEN] = z_mrsh_cmrt_kdc_open,
        [C_SYSCALL_CMRT_KDC_CLOSE] = z_mrsh_cmrt_kdc_close,
        [C_SYSCALL_CMRT_KDC_DERIVE_KEY] = z_mrsh_cmrt_kdc_derive_key,
        [C_SYSCALL_CMRT_KDC_DIVERSIFY_KEY] = z_mrsh_cmrt_kdc_diversify_key,
        [C_SYSCALL_CMRT_KDC_SYNC] = z_mrsh_cmrt_kdc_sync,
        [C_SYSCALL_CMRT_KTC_OPEN] = z_mrsh_cmrt_ktc_open,
        [C_SYSCALL_CMRT_KTC_CLOSE] = z_mrsh_cmrt_ktc_close,
        [C_SYSCALL_CMRT_KTC_EXPORT] = z_mrsh_cmrt_ktc_export,
        [C_SYSCALL_CMRT_KTC_SYNC] = z_mrsh_cmrt_ktc_sync,
        [C_SYSCALL_CMRT_OMC_OPEN] = z_mrsh_cmrt_omc_open,
        [C_SYSCALL_CMRT_OMC_CLOSE] = z_mrsh_cmrt_omc_close,
        [C_SYSCALL_CMRT_OMC_READ] = z_mrsh_cmrt_omc_read,
        [C_SYSCALL_CMRT_OMC_WRITE] = z_mrsh_cmrt_omc_write,
        [C_SYSCALL_CMRT_OMC_OBLITERATE] = z_mrsh_cmrt_omc_obliterate,
        [C_SYSCALL_CMRT_OMC_SYNC] = z_mrsh_cmrt_omc_sync,
        [C_SYSCALL_CMRT_OEC_READ] = z_mrsh_cmrt_oec_read,
        [C_SYSCALL_CMRT_OEC_WRITE] = z_mrsh_cmrt_oec_write,
        [C_SYSCALL_CMRT_OEC_COMMIT] = z_mrsh_cmrt_oec_commit,
        [C_SYSCALL_CMRT_SAC_READ32] = z_mrsh_cmrt_sac_read32,
        [C_SYSCALL_CMRT_SAC_WRITE32] = z_mrsh_cmrt_sac_write32,
        [C_SYSCALL_CMRT_SAC_MEMCPY] = z_mrsh_cmrt_sac_memcpy,
        [C_SYSCALL_CMRT_SIC_OPEN] = z_mrsh_cmrt_sic_open,
        [C_SYSCALL_CMRT_SIC_CLOSE] = z_mrsh_cmrt_sic_close,
        [C_SYSCALL_CMRT_SIC_READ] = z_mrsh_cmrt_sic_read,
        [C_SYSCALL_CMRT_SIC_WRITE] = z_mrsh_cmrt_sic_write,
        [C_SYSCALL_CMRT_SIC_SYNC] = z_mrsh_cmrt_sic_sync,
        [C_SYSCALL_CMRT_SID_OPEN] = z_mrsh_cmrt_sid_open,
        [C_SYSCALL_CMRT_SID_CLOSE] = z_mrsh_cmrt_sid_close,
        [C_SYSCALL_CMRT_SID_WATCH] = z_mrsh_cmrt_sid_watch,
        [C_SYSCALL_CMRT_SID_SYNC] = z_mrsh_cmrt_sid_sync,
        [C_SYSCALL_CMRT_TMC_OPEN] = z_mrsh_cmrt_tmc_open,
        [C_SYSCALL_CMRT_TMC_CLOSE] = z_mrsh_cmrt_tmc_close,
        [C_SYSCALL_CMRT_TMC_COMMAND] = z_mrsh_cmrt_tmc_command,
        [C_SYSCALL_CMRT_TMC_SYNC] = z_mrsh_cmrt_tmc_sync,
        [C_SYSCALL_CMRT_WDT_OPEN] = z_mrsh_cmrt_wdt_open,
        [C_SYSCALL_CMRT_WDT_CLOSE] = z_mrsh_cmrt_wdt_close,
        [C_SYSCALL_CMRT_WDT_SYNC] = z_mrsh_cmrt_wdt_sync,
        [C_SYSCALL_TEEDEV_PAGE_CRYPTO] = z_mrsh_teedev_page_crypto,
        [C_SYSCALL_TEEDEV_DERIVE_KEY] = z_mrsh_teedev_derive_key,
        [C_SYSCALL_TEEDEV_DMAC_BLOCK_ERASE] = z_mrsh_teedev_dmac_block_erase,
        [C_SYSCALL_TEEDEV_DMAC_PAGE_READ] = z_mrsh_teedev_dmac_page_read,
        [C_SYSCALL_TEEDEV_DMAC_PAGE_PROG] = z_mrsh_teedev_dmac_page_prog,
        [C_SYSCALL_TEEDEV_FLASH_BLOCK_ERASE] = z_mrsh_teedev_flash_block_erase,
        [C_SYSCALL_TEEDEV_FLASH_PAGE_READ] = z_mrsh_teedev_flash_page_read,
        [C_SYSCALL_TEEDEV_FLASH_PAGE_PROG] = z_mrsh_teedev_flash_page_prog,
        [C_SYSCALL_TEEDEV_OTP_BLOCK_ERASE] = z_mrsh_teedev_otp_block_erase,
        [C_SYSCALL_TEEDEV_OTP_PAGE_READ] = z_mrsh_teedev_otp_page_read,
        [C_SYSCALL_TEEDEV_OTP_PAGE_PROG] = z_mrsh_teedev_otp_page_prog,
        [C_SYSCALL_USER_FAULT] = z_mrsh_user_fault,
        [C_SYSCALL_CLOCK_GETTIME] = z_mrsh_clock_gettime,
        [C_SYSCALL_Z_ERRNO] = z_mrsh_z_errno,
        [C_SYSCALL_ZEPHYR_READ_STDIN] = z_mrsh_zephyr_read_stdin,
        [C_SYSCALL_ZEPHYR_WRITE_STDOUT] = z_mrsh_zephyr_write_stdout,
        [C_SYSCALL_ZEPHYR_FPUTC] = z_mrsh_zephyr_fputc,
        [C_SYSCALL_ZEPHYR_FWRITE] = z_mrsh_zephyr_fwrite,
        [C_SYSCALL_CMRT_AES_CCM_ENCODE_AAD] = z_mrsh_cmrt_aes_ccm_encode_aad,
        [C_SYSCALL_CMRT_AES_CCM_ENCODE_NONCE] = z_mrsh_cmrt_aes_ccm_encode_nonce,
        [C_SYSCALL_CMRT_PKE_FFDH] = z_mrsh_cmrt_pke_ffdh,
        [C_SYSCALL_CMRT_PKE_FFDH_PRIVATE_KEYGEN] = z_mrsh_cmrt_pke_ffdh_private_keygen,
        [C_SYSCALL_CMRT_PKE_FFDH_VERIFY] = z_mrsh_cmrt_pke_ffdh_verify,
        [C_SYSCALL_CMRT_PKE_FFDH_PARMGEN] = z_mrsh_cmrt_pke_ffdh_parmgen,
        [C_SYSCALL_CMRT_PKE_GET_CURVE] = z_mrsh_cmrt_pke_get_curve,
        [C_SYSCALL_CMRT_PKE_GET_CURVE_LENGTH] = z_mrsh_cmrt_pke_get_curve_length,
        [C_SYSCALL_CMRT_PKE_OPEN] = z_mrsh_cmrt_pke_open,
        [C_SYSCALL_CMRT_PKE_CLOSE] = z_mrsh_cmrt_pke_close,
        [C_SYSCALL_CMRT_PKE_SYNC] = z_mrsh_cmrt_pke_sync,
        [C_SYSCALL_CMRT_PKE_FLUSH] = z_mrsh_cmrt_pke_flush,
        [C_SYSCALL_CMRT_PKE_ECDSA_VERIFY] = z_mrsh_cmrt_pke_ecdsa_verify,
        [C_SYSCALL_CMRT_PKE_ECDSA_VERIFY_HASH] = z_mrsh_cmrt_pke_ecdsa_verify_hash,
        [C_SYSCALL_CMRT_PKE_ECDSA_SIGN] = z_mrsh_cmrt_pke_ecdsa_sign,
        [C_SYSCALL_CMRT_PKE_ECDSA_SIGN_HASH] = z_mrsh_cmrt_pke_ecdsa_sign_hash,
        [C_SYSCALL_CMRT_PKE_ECDSA_KEYGEN] = z_mrsh_cmrt_pke_ecdsa_keygen,
        [C_SYSCALL_CMRT_PKE_RSA_PUBLIC_KEY_PRIMITIVE] = z_mrsh_cmrt_pke_rsa_public_key_primitive,
        // [C_SYSCALL_CMRT_PKE_BLIND_PRIVATE_KEY] = z_mrsh_cmrt_pke_blind_private_key,
        [C_SYSCALL_CMRT_PKE_ECDH_KEYGEN] = z_mrsh_cmrt_pke_ecdh_keygen,
        [C_SYSCALL_CMRT_PKE_ECDH] = z_mrsh_cmrt_pke_ecdh,
        [C_SYSCALL_CMRT_PKE_RFC7748_KEYGEN] = z_mrsh_cmrt_pke_rfc7748_keygen,
        [C_SYSCALL_CMRT_PKE_RFC7748] = z_mrsh_cmrt_pke_rfc7748,
        [C_SYSCALL_CMRT_PKE_EDDSA_SIGN] = z_mrsh_cmrt_pke_eddsa_sign,
        [C_SYSCALL_CMRT_PKE_EDDSA_VERIFY] = z_mrsh_cmrt_pke_eddsa_verify,
        [C_SYSCALL_CMRT_PKE_EDDSA_KEYGEN] = z_mrsh_cmrt_pke_eddsa_keygen,
        [C_SYSCALL_CMRT_PKE_VALIDATE_ECC_XY_KEY] = z_mrsh_cmrt_pke_validate_ecc_xy_key,
        [C_SYSCALL_CMRT_GET_RANDOM] = z_mrsh_cmrt_get_random,
        [C_SYSCALL_FBOOT_CREATE_ROOT] = z_mrsh_fboot_create_root,
        [C_SYSCALL_FBOOT_OBLITERATE_ROOT] = z_mrsh_fboot_obliterate_root,
        [C_SYSCALL_FBOOT_GET_IMAGE_VERSION] = z_mrsh_fboot_get_image_version,
        [C_SYSCALL_CMRT_INIT_TMC_CONFIG] = z_mrsh_cmrt_init_tmc_config,
        [C_SYSCALL_CMRT_CSHC_OPEN] = z_mrsh_cmrt_cshc_open,
        [C_SYSCALL_CMRT_WHC_OPEN] = z_mrsh_cmrt_whc_open,
        [C_SYSCALL_CMRT_HC2_OPEN] = z_mrsh_cmrt_hc2_open,
        [C_SYSCALL_CMRT_PKE_RSA_SIGN] = z_mrsh_cmrt_pke_rsa_sign,
        [C_SYSCALL_CMRT_PKE_RSA_KEY_GEN] = z_mrsh_cmrt_pke_rsa_key_gen,
        [C_SYSCALL_CMRT_PKE_RSA_CRT_KEY_GEN] = z_mrsh_cmrt_pke_rsa_crt_key_gen,
        [C_SYSCALL_CMRT_PKE_RSA_CRT_SIGN] = z_mrsh_cmrt_pke_rsa_crt_sign,
        [C_SYSCALL_CMRT_PMU_LOW_POWER] = z_mrsh_cmrt_pmu_low_power,
        [C_SYSCALL_FBOOT_HALT] = z_mrsh_fboot_halt,
        [C_SYSCALL_FBOOT_REBOOT] = z_mrsh_fboot_reboot,
        [C_SYSCALL_FBOOT_RESET] = z_mrsh_fboot_reset,
        [C_SYSCALL_FBOOT_RESET_INFO] = z_mrsh_fboot_reset_info,
        [C_SYSCALL_FBOOT_GET_ENFORCED_VERSION] = z_mrsh_fboot_get_enforced_version,
        [C_SYSCALL_FBOOT_SET_ENFORCED_VERSION] = z_mrsh_fboot_set_enforced_version,
        [C_SYSCALL_FBOOT_DATA_STORE_READ] = z_mrsh_fboot_data_store_read,
        [C_SYSCALL_FBOOT_DATA_STORE_WRITE] = z_mrsh_fboot_data_store_write,
        [C_SYSCALL_FBOOT_DATA_STORE_GRANT] = z_mrsh_fboot_data_store_grant,
        [C_SYSCALL_CMRT_SIC_READ_REG] = z_mrsh_cmrt_sic_read_reg,
        [C_SYSCALL_CMRT_SIC_WRITE_REG] = z_mrsh_cmrt_sic_write_reg,
        [C_SYSCALL_CMRT_WDT_FEED] = z_mrsh_cmrt_wdt_feed,
        [C_SYSCALL_CMRT_PERF_REF] = z_mrsh_cmrt_perf_ref,
        [C_SYSCALL_CMRT_ACCESS] = z_mrsh_cmrt_access,
        [C_SYSCALL_CMRT_UPTIME_GET] = z_mrsh_cmrt_uptime_get,
        [C_SYSCALL_CMRT_GET_ENTROPY] = z_mrsh_cmrt_get_entropy,
        [C_SYSCALL_CMRT_EXIT_CONTAINER] = z_mrsh_cmrt_exit_container,
        [C_SYSCALL_CMRT_SAC_READ8] = z_mrsh_cmrt_sac_read8,
        [C_SYSCALL_CMRT_SAC_WRITE8] = z_mrsh_cmrt_sac_write8,
        [C_SYSCALL_BAD] = handler_bad_syscall /* must be last! */
};
"""

list_template = """
/* auto-generated by gen_syscalls.py, don't edit */
#ifndef ZEPHYR_SYSCALL_LIST_H
#define ZEPHYR_SYSCALL_LIST_H

%s

#ifndef _ASMLANGUAGE

#include <stdint.h>

#endif /* _ASMLANGUAGE */

#endif /* ZEPHYR_SYSCALL_LIST_H */
"""

# Fixed CMRT user container syscall ids. This could be generated
# from a file but let's make it easy for now...
list_container = """
#define C_SYSCALL_BASE 0x800
#define C_SYSCALL_CMRT_AES_AE_FINAL 0
#define C_SYSCALL_CMRT_AES_CLOSE 1
#define C_SYSCALL_CMRT_AES_FINAL 2
#define C_SYSCALL_CMRT_AES_FINAL_AAD 3
#define C_SYSCALL_CMRT_AES_INIT 4
#define C_SYSCALL_CMRT_AES_KDC_CMD 5
#define C_SYSCALL_CMRT_AES_OPEN 6
#define C_SYSCALL_CMRT_AES_UPDATE 7
#define C_SYSCALL_CMRT_AES_UPDATE_AAD 8
#define C_SYSCALL_CMRT_AES_XTS_SET_OFFSET 9
#define C_SYSCALL_CMRT_CCP_AE_FINAL 10
#define C_SYSCALL_CMRT_CCP_CLOSE 11
#define C_SYSCALL_CMRT_CCP_FINAL 12
#define C_SYSCALL_CMRT_CCP_FINAL_AAD 13
#define C_SYSCALL_CMRT_CCP_INIT 14
#define C_SYSCALL_CMRT_CCP_INVALIDATE_KEY 15
#define C_SYSCALL_CMRT_CCP_OPEN 16
#define C_SYSCALL_CMRT_CCP_UPDATE 17
#define C_SYSCALL_CMRT_CCP_UPDATE_AAD 18
#define C_SYSCALL_CMRT_CC_ASSERT 19
#define C_SYSCALL_CMRT_CC_CLOSE 20
#define C_SYSCALL_CMRT_CC_MIX 21
#define C_SYSCALL_CMRT_CC_OPEN 22
#define C_SYSCALL_CMRT_CC_SYNC 23
#define C_SYSCALL_CMRT_DMAC_CLOSE 24
#define C_SYSCALL_CMRT_DMAC_DATA 25
#define C_SYSCALL_CMRT_DMAC_FILL 26
#define C_SYSCALL_CMRT_DMAC_OPEN 27
#define C_SYSCALL_CMRT_DMAC_SYNC 28
#define C_SYSCALL_CMRT_FMC_CLOSE 29
#define C_SYSCALL_CMRT_FMC_READ 30
#define C_SYSCALL_CMRT_FMC_WRITE 31
#define C_SYSCALL_CMRT_FMC_GPIO_READ 32
#define C_SYSCALL_CMRT_FMC_GPIO_WRITE 33
#define C_SYSCALL_CMRT_FMC_OPEN 34
#define C_SYSCALL_CMRT_FMC_SET_DEBUG_MODE 35
#define C_SYSCALL_CMRT_HC_CLOSE 36
#define C_SYSCALL_CMRT_HC_FINAL 37
#define C_SYSCALL_CMRT_HC_INIT 38
#define C_SYSCALL_CMRT_HC_KDC_CMD 39
#define C_SYSCALL_CMRT_HC_OPEN 40
#define C_SYSCALL_CMRT_HC_UPDATE 41
#define C_SYSCALL_CMRT_KDC_CLOSE 42
#define C_SYSCALL_CMRT_KDC_DERIVE_KEY 43
#define C_SYSCALL_CMRT_KDC_DIVERSIFY_KEY 44
#define C_SYSCALL_CMRT_KDC_OPEN 45
#define C_SYSCALL_CMRT_KDC_SYNC 46
#define C_SYSCALL_CMRT_KTC_CLOSE 47
#define C_SYSCALL_CMRT_KTC_EXPORT 48
#define C_SYSCALL_CMRT_KTC_OPEN 49
#define C_SYSCALL_CMRT_KTC_SYNC 50
#define C_SYSCALL_CMRT_OEC_COMMIT 51
#define C_SYSCALL_CMRT_OEC_READ 52
#define C_SYSCALL_CMRT_OEC_WRITE 53
#define C_SYSCALL_CMRT_OMC_CLOSE 54
#define C_SYSCALL_CMRT_OMC_OBLITERATE 55
#define C_SYSCALL_CMRT_OMC_OPEN 56
#define C_SYSCALL_CMRT_OMC_READ 57
#define C_SYSCALL_CMRT_OMC_SYNC 58
#define C_SYSCALL_CMRT_OMC_WRITE 59
#define C_SYSCALL_CMRT_SAC_MEMCPY 60
#define C_SYSCALL_CMRT_SAC_READ32 61
#define C_SYSCALL_CMRT_SAC_WRITE32 62
#define C_SYSCALL_CMRT_SIC_CLOSE 63
#define C_SYSCALL_CMRT_SIC_OPEN 64
#define C_SYSCALL_CMRT_SIC_READ 65
#define C_SYSCALL_CMRT_SIC_SYNC 66
#define C_SYSCALL_CMRT_SIC_WRITE 67
#define C_SYSCALL_CMRT_SID_CLOSE 68
#define C_SYSCALL_CMRT_SID_OPEN 69
#define C_SYSCALL_CMRT_SID_SYNC 70
#define C_SYSCALL_CMRT_SID_WATCH 71
#define C_SYSCALL_CMRT_TMC_CLOSE 72
#define C_SYSCALL_CMRT_TMC_COMMAND 73
#define C_SYSCALL_CMRT_TMC_OPEN 74
#define C_SYSCALL_CMRT_TMC_SYNC 75
#define C_SYSCALL_CMRT_WAIT 76
#define C_SYSCALL_CMRT_WDT_CLOSE 77
#define C_SYSCALL_CMRT_WDT_OPEN 78
#define C_SYSCALL_CMRT_WDT_SYNC 79
#define C_SYSCALL_TEEDEV_DERIVE_KEY 80
#define C_SYSCALL_TEEDEV_DMAC_BLOCK_ERASE 81
#define C_SYSCALL_TEEDEV_DMAC_PAGE_PROG 82
#define C_SYSCALL_TEEDEV_DMAC_PAGE_READ 83
#define C_SYSCALL_TEEDEV_FLASH_BLOCK_ERASE 84
#define C_SYSCALL_TEEDEV_FLASH_PAGE_PROG 85
#define C_SYSCALL_TEEDEV_FLASH_PAGE_READ 86
#define C_SYSCALL_TEEDEV_OTP_BLOCK_ERASE 87
#define C_SYSCALL_TEEDEV_OTP_PAGE_PROG 88
#define C_SYSCALL_TEEDEV_OTP_PAGE_READ 89
#define C_SYSCALL_TEEDEV_PAGE_CRYPTO 90
#define C_SYSCALL_USER_FAULT 91
#define C_SYSCALL_CLOCK_GETTIME 92
#define C_SYSCALL_Z_ERRNO 93
#define C_SYSCALL_ZEPHYR_READ_STDIN 94
#define C_SYSCALL_ZEPHYR_WRITE_STDOUT 95
#define C_SYSCALL_ZEPHYR_FPUTC 96
#define C_SYSCALL_ZEPHYR_FWRITE 97
#define C_SYSCALL_CMRT_AES_CCM_ENCODE_AAD 98
#define C_SYSCALL_CMRT_AES_CCM_ENCODE_NONCE 99
#define C_SYSCALL_CMRT_PKE_FFDH 100
#define C_SYSCALL_CMRT_PKE_FFDH_PRIVATE_KEYGEN 101
#define C_SYSCALL_CMRT_PKE_FFDH_VERIFY 102
#define C_SYSCALL_CMRT_PKE_FFDH_PARMGEN 103
#define C_SYSCALL_CMRT_PKE_GET_CURVE 104
#define C_SYSCALL_CMRT_PKE_GET_CURVE_LENGTH 105
#define C_SYSCALL_CMRT_PKE_OPEN 106
#define C_SYSCALL_CMRT_PKE_CLOSE 107
#define C_SYSCALL_CMRT_PKE_SYNC 108
#define C_SYSCALL_CMRT_PKE_FLUSH 109
#define C_SYSCALL_CMRT_PKE_ECDSA_VERIFY 110
#define C_SYSCALL_CMRT_PKE_ECDSA_VERIFY_HASH 111
#define C_SYSCALL_CMRT_PKE_ECDSA_SIGN 112
#define C_SYSCALL_CMRT_PKE_ECDSA_SIGN_HASH 113
#define C_SYSCALL_CMRT_PKE_ECDSA_KEYGEN 114
#define C_SYSCALL_CMRT_PKE_RSA_PUBLIC_KEY_PRIMITIVE 115
// #define C_SYSCALL_CMRT_PKE_BLIND_PRIVATE_KEY 116
#define C_SYSCALL_CMRT_PKE_ECDH_KEYGEN 117
#define C_SYSCALL_CMRT_PKE_ECDH 118
#define C_SYSCALL_CMRT_PKE_RFC7748_KEYGEN 119
#define C_SYSCALL_CMRT_PKE_RFC7748 120
#define C_SYSCALL_CMRT_PKE_EDDSA_SIGN 121
#define C_SYSCALL_CMRT_PKE_EDDSA_VERIFY 122
#define C_SYSCALL_CMRT_PKE_EDDSA_KEYGEN 123
#define C_SYSCALL_CMRT_PKE_VALIDATE_ECC_XY_KEY 124
#define C_SYSCALL_CMRT_GET_RANDOM 125
#define C_SYSCALL_FBOOT_CREATE_ROOT 126
#define C_SYSCALL_FBOOT_OBLITERATE_ROOT 127
#define C_SYSCALL_FBOOT_GET_IMAGE_VERSION 128
#define C_SYSCALL_CMRT_INIT_TMC_CONFIG 129
#define C_SYSCALL_CMRT_CSHC_OPEN 130
#define C_SYSCALL_CMRT_WHC_OPEN 131
#define C_SYSCALL_CMRT_HC2_OPEN 132
#define C_SYSCALL_CMRT_PKE_RSA_SIGN 133
#define C_SYSCALL_CMRT_PKE_RSA_KEY_GEN 134
#define C_SYSCALL_CMRT_PKE_RSA_CRT_KEY_GEN 135
#define C_SYSCALL_CMRT_PKE_RSA_CRT_SIGN 136
#define C_SYSCALL_CMRT_PMU_LOW_POWER 137
#define C_SYSCALL_FBOOT_HALT 138
#define C_SYSCALL_FBOOT_REBOOT 139
#define C_SYSCALL_FBOOT_RESET 140
#define C_SYSCALL_FBOOT_RESET_INFO 141
#define C_SYSCALL_FBOOT_GET_ENFORCED_VERSION 142
#define C_SYSCALL_FBOOT_SET_ENFORCED_VERSION 143
#define C_SYSCALL_FBOOT_DATA_STORE_READ 144
#define C_SYSCALL_FBOOT_DATA_STORE_WRITE 145
#define C_SYSCALL_FBOOT_DATA_STORE_GRANT 146
#define C_SYSCALL_CMRT_SIC_READ_REG 147
#define C_SYSCALL_CMRT_SIC_WRITE_REG 148
#define C_SYSCALL_CMRT_WDT_FEED 149
#define C_SYSCALL_CMRT_PERF_REF 150
#define C_SYSCALL_CMRT_ACCESS 151
#define C_SYSCALL_CMRT_UPTIME_GET 152
#define C_SYSCALL_CMRT_GET_ENTROPY 153
#define C_SYSCALL_CMRT_EXIT_CONTAINER 154
#define C_SYSCALL_CMRT_SAC_READ8 155
#define C_SYSCALL_CMRT_SAC_WRITE8 156
#define C_SYSCALL_BAD 167 /* must be last! */
#define C_SYSCALL_LIMIT 168
"""

syscall_template = """
/* auto-generated by gen_syscalls.py, don't edit */
%s

#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#include <linker/sections.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#if !defined(__XCC__)
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

%s

#ifdef __cplusplus
}
#endif

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic pop
#endif

#endif
#endif /* include guard */
"""

handler_template = """
extern uintptr_t z_hdlr_%s(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3,
                uintptr_t arg4, uintptr_t arg5, uintptr_t arg6, void *ssf);
"""

weak_template = """
__weak ALIAS_OF(handler_no_syscall)
uintptr_t %s(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3,
         uintptr_t arg4, uintptr_t arg5, uintptr_t arg6, void *ssf);
"""


typename_regex = re.compile(r'(.*?)([A-Za-z0-9_]+)$')


class SyscallParseException(Exception):
    pass


def typename_split(item):
    if "[" in item:
        raise SyscallParseException(
            "Please pass arrays to syscalls as pointers, unable to process '%s'" %
            item)

    if "(" in item:
        raise SyscallParseException(
            "Please use typedefs for function pointers")

    mo = typename_regex.match(item)
    if not mo:
        raise SyscallParseException("Malformed system call invocation")

    m = mo.groups()
    return (m[0].strip(), m[1])

def need_split(argtype):
    return (not args.long_registers) and (argtype in types64)

# Note: "lo" and "hi" are named in little endian conventions,
# but it doesn't matter as long as they are consistently
# generated.
def union_decl(type):
    return "union { struct { uintptr_t lo, hi; } split; %s val; }" % type

def wrapper_defs(func_name, func_type, args):
    ret64 = need_split(func_type)
    mrsh_args = [] # List of rvalue expressions for the marshalled invocation
    split_args = []
    nsplit = 0
    for argtype, argname in args:
        if need_split(argtype):
            split_args.append((argtype, argname))
            mrsh_args.append("parm%d.split.lo" % nsplit)
            mrsh_args.append("parm%d.split.hi" % nsplit)
            nsplit += 1
        else:
            mrsh_args.append("*(uintptr_t *)&" + argname)

    if ret64:
        mrsh_args.append("(uintptr_t)&ret64")

    decl_arglist = ", ".join([" ".join(argrec) for argrec in args]) or "void"

    wrap = "extern %s z_impl_%s(%s);\n" % (func_type, func_name, decl_arglist)
    wrap += "\n"
    wrap += "__pinned_func\n"
    wrap += "static inline %s %s(%s)\n" % (func_type, func_name, decl_arglist)
    wrap += "{\n"
    wrap += "#ifdef CONFIG_USERSPACE\n"
    wrap += ("\t" + "uint64_t ret64;\n") if ret64 else ""
    wrap += "\t" + "if (z_syscall_trap()) {\n"

    for parmnum, rec in enumerate(split_args):
        (argtype, argname) = rec
        wrap += "\t\t%s parm%d;\n" % (union_decl(argtype), parmnum)
        wrap += "\t\t" + "parm%d.val = %s;\n" % (parmnum, argname)

    if len(mrsh_args) > 6:
        wrap += "\t\t" + "uintptr_t more[] = {\n"
        wrap += "\t\t\t" + (",\n\t\t\t".join(mrsh_args[5:])) + "\n"
        wrap += "\t\t" + "};\n"
        mrsh_args[5:] = ["(uintptr_t) &more"]

    syscall_id = "K_SYSCALL_" + func_name.upper()
    invoke = ("arch_syscall_invoke%d(%s)"
              % (len(mrsh_args),
                 ", ".join(mrsh_args + [syscall_id])))

    # Coverity does not understand syscall mechanism
    # and will already complain when any function argument
    # is not of exact size as uintptr_t. So tell Coverity
    # to ignore this particular rule here.
    wrap += "\t\t/* coverity[OVERRUN] */\n"

    if ret64:
        wrap += "\t\t" + "(void)%s;\n" % invoke
        wrap += "\t\t" + "return (%s)ret64;\n" % func_type
    elif func_type == "void":
        wrap += "\t\t" + "%s;\n" % invoke
        wrap += "\t\t" + "return;\n"
    else:
        wrap += "\t\t" + "return (%s) %s;\n" % (func_type, invoke)

    wrap += "\t" + "}\n"
    wrap += "#endif\n"

    # Otherwise fall through to direct invocation of the impl func.
    # Note the compiler barrier: that is required to prevent code from
    # the impl call from being hoisted above the check for user
    # context.
    impl_arglist = ", ".join([argrec[1] for argrec in args])
    impl_call = "z_impl_%s(%s)" % (func_name, impl_arglist)
    wrap += "\t" + "compiler_barrier();\n"
    wrap += "\t" + "%s%s;\n" % ("return " if func_type != "void" else "",
                               impl_call)

    wrap += "}\n"

    return wrap

# Returns an expression for the specified (zero-indexed!) marshalled
# parameter to a syscall, with handling for a final "more" parameter.
def mrsh_rval(mrsh_num, total):
    if mrsh_num < 5 or total <= 6:
        return "arg%d" % mrsh_num
    else:
        return "(((uintptr_t *)more)[%d])" % (mrsh_num - 5)

def marshall_defs(func_name, func_type, args):
    mrsh_name = "z_mrsh_" + func_name

    nmrsh = 0        # number of marshalled uintptr_t parameter
    vrfy_parms = []  # list of (arg_num, mrsh_or_parm_num, bool_is_split)
    split_parms = [] # list of a (arg_num, mrsh_num) for each split
    for i, (argtype, _) in enumerate(args):
        if need_split(argtype):
            vrfy_parms.append((i, len(split_parms), True))
            split_parms.append((i, nmrsh))
            nmrsh += 2
        else:
            vrfy_parms.append((i, nmrsh, False))
            nmrsh += 1

    # Final argument for a 64 bit return value?
    if need_split(func_type):
        nmrsh += 1

    decl_arglist = ", ".join([" ".join(argrec) for argrec in args])
    mrsh = "extern %s z_vrfy_%s(%s);\n" % (func_type, func_name, decl_arglist)

    mrsh += "uintptr_t %s(uintptr_t arg0, uintptr_t arg1, uintptr_t arg2,\n" % mrsh_name
    if nmrsh <= 6:
        mrsh += "\t\t" + "uintptr_t arg3, uintptr_t arg4, uintptr_t arg5, void *ssf)\n"
    else:
        mrsh += "\t\t" + "uintptr_t arg3, uintptr_t arg4, void *more, void *ssf)\n"
    mrsh += "{\n"
    mrsh += "\t" + "_current->syscall_frame = ssf;\n"

    for unused_arg in range(nmrsh, 6):
        mrsh += "\t(void) arg%d;\t/* unused */\n" % unused_arg

    if nmrsh > 6:
        mrsh += ("\tZ_OOPS(Z_SYSCALL_MEMORY_READ(more, "
                 + str(nmrsh - 6) + " * sizeof(uintptr_t)));\n")

    for i, split_rec in enumerate(split_parms):
        arg_num, mrsh_num = split_rec
        arg_type = args[arg_num][0]
        mrsh += "\t%s parm%d;\n" % (union_decl(arg_type), i)
        mrsh += "\t" + "parm%d.split.lo = %s;\n" % (i, mrsh_rval(mrsh_num,
                                                                 nmrsh))
        mrsh += "\t" + "parm%d.split.hi = %s;\n" % (i, mrsh_rval(mrsh_num + 1,
                                                                 nmrsh))
    # Finally, invoke the verify function
    out_args = []
    for i, argn, is_split in vrfy_parms:
        if is_split:
            out_args.append("parm%d.val" % argn)
        else:
            out_args.append("*(%s*)&%s" % (args[i][0], mrsh_rval(argn, nmrsh)))

    vrfy_call = "z_vrfy_%s(%s)\n" % (func_name, ", ".join(out_args))

    if func_type == "void":
        mrsh += "\t" + "%s;\n" % vrfy_call
        mrsh += "\t" + "_current->syscall_frame = NULL;\n"
        mrsh += "\t" + "return 0;\n"
    else:
        mrsh += "\t" + "%s ret = %s;\n" % (func_type, vrfy_call)

        if need_split(func_type):
            ptr = "((uint64_t *)%s)" % mrsh_rval(nmrsh - 1, nmrsh)
            mrsh += "\t" + "Z_OOPS(Z_SYSCALL_MEMORY_WRITE(%s, 8));\n" % ptr
            mrsh += "\t" + "*%s = ret;\n" % ptr
            mrsh += "\t" + "_current->syscall_frame = NULL;\n"
            mrsh += "\t" + "return 0;\n"
        else:
            mrsh += "\t" + "_current->syscall_frame = NULL;\n"
            mrsh += "\t" + "return (uintptr_t) ret;\n"

    mrsh += "}\n"

    return mrsh, mrsh_name

def analyze_fn(match_group):
    func, args = match_group

    try:
        if args == "void":
            args = []
        else:
            args = [typename_split(a.strip()) for a in args.split(",")]

        func_type, func_name = typename_split(func)
    except SyscallParseException:
        sys.stderr.write("In declaration of %s\n" % func)
        raise

    sys_id = "K_SYSCALL_" + func_name.upper()

    marshaller = None
    marshaller, handler = marshall_defs(func_name, func_type, args)
    invocation = wrapper_defs(func_name, func_type, args)

    # Entry in _k_syscall_table
    table_entry = "[%s] = %s" % (sys_id, handler)

    return (handler, invocation, marshaller, sys_id, table_entry)

def parse_args():
    global args
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument("-i", "--json-file", required=True,
                        help="Read syscall information from json file")
    parser.add_argument("-d", "--syscall-dispatch", required=True,
                        help="output C system call dispatch table file")
    parser.add_argument("-l", "--syscall-list", required=True,
                        help="output C system call list header")
    parser.add_argument("-o", "--base-output", required=True,
                        help="Base output directory for syscall macro headers")
    parser.add_argument("-s", "--split-type", action="append",
                        help="A long type that must be split/marshalled on 32-bit systems")
    parser.add_argument("-x", "--long-registers", action="store_true",
                        help="Indicates we are on system with 64-bit registers")
    args = parser.parse_args()


def main():
    parse_args()

    if args.split_type is not None:
        for t in args.split_type:
            types64.append(t)

    with open(args.json_file, 'r') as fd:
        syscalls = json.load(fd)

    invocations = {}
    mrsh_defs = {}
    mrsh_includes = {}
    ids = []
    table_entries = []
    handlers = []

    for match_group, fn in syscalls:
        handler, inv, mrsh, sys_id, entry = analyze_fn(match_group)

        if fn not in invocations:
            invocations[fn] = []

        invocations[fn].append(inv)
        ids.append(sys_id)
        table_entries.append(entry)
        handlers.append(handler)

        if mrsh:
            syscall = typename_split(match_group[0])[1]
            mrsh_defs[syscall] = mrsh
            mrsh_includes[syscall] = "#include <syscalls/%s>" % fn

    with open(args.syscall_dispatch, "w") as fp:
        table_entries.append("[K_SYSCALL_BAD] = handler_bad_syscall")

        weak_defines = "".join([weak_template % name
                                for name in handlers
                                if not name in noweak])

        # The "noweak" ones just get a regular declaration
        weak_defines += "\n".join(["extern uintptr_t %s(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5, uintptr_t arg6, void *ssf);"
                                   % s for s in noweak])

        fp.write(table_template % (weak_defines,
                                   ",\n\t".join(table_entries)))

        # Fixed CMRT user container syscall table
        fp.write(table_container)

    # Listing header emitted to stdout
    ids.sort()
    ids.extend(["K_SYSCALL_BAD", "K_SYSCALL_LIMIT"])

    ids_as_defines = ""
    for i, item in enumerate(ids):
        ids_as_defines += "#define {} {}\n".format(item, i)

    ids_as_defines += list_container

    with open(args.syscall_list, "w") as fp:
        fp.write(list_template % ids_as_defines)

    os.makedirs(args.base_output, exist_ok=True)
    for fn, invo_list in invocations.items():
        out_fn = os.path.join(args.base_output, fn)

        ig = re.sub("[^a-zA-Z0-9]", "_", "Z_INCLUDE_SYSCALLS_" + fn).upper()
        include_guard = "#ifndef %s\n#define %s\n" % (ig, ig)
        header = syscall_template % (include_guard, "\n\n".join(invo_list))

        with open(out_fn, "w") as fp:
            fp.write(header)

    # Likewise emit _mrsh.c files for syscall inclusion
    for fn in mrsh_defs:
        mrsh_fn = os.path.join(args.base_output, fn + "_mrsh.c")

        with open(mrsh_fn, "w") as fp:
            fp.write("/* auto-generated by gen_syscalls.py, don't edit */\n")
            fp.write("#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)\n")
            fp.write("#pragma GCC diagnostic push\n")
            fp.write("#endif\n")
            fp.write("#ifdef __GNUC__\n")
            fp.write("#pragma GCC diagnostic ignored \"-Wstrict-aliasing\"\n")
            fp.write("#endif\n")
            fp.write(mrsh_includes[fn] + "\n")
            fp.write("\n")
            fp.write(mrsh_defs[fn] + "\n")
            fp.write("#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)\n")
            fp.write("#pragma GCC diagnostic pop\n")
            fp.write("#endif\n")

if __name__ == "__main__":
    main()
