CONFIG_CMRT_V1=y
CONFIG_MULTITHREADING=y
CONFIG_POLL=y
CONFIG_MAIN_THREAD_PRIORITY=14
CONFIG_SUPERVISOR_MODE=y
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_CMRT_SCRATCHPAD=y
CONFIG_CMRT_AES=y
CONFIG_CMRT_RSA=y
CONFIG_CMRT_RSA_CRT=y
#CONFIG_PIX=y
CONFIG_TEEFS=y
CONFIG_TEEFS_MAX_INSTANCES=1
CONFIG_TEEFS_MAX_PAGES=15
CONFIG_TEEFS_MAX_FILES=4
CONFIG_TEEFS_MAX_PAGE_SIZE=8
CONFIG_TEEFS_MAX_DIRS=1
CONFIG_TEEFS_MAX_CACHE_PAGES=4
CONFIG_TEEFS_MAX_BAD_BLOCKS=1
CONFIG_TEEFS_MAX_NAMELEN=64
CONFIG_CMRT_TEEDEV_DMAC=y
CONFIG_TEEDEV_DMAC_BLOCK_SIZE=12
CONFIG_TEEDEV_DMAC_PAGE_SIZE=8
CONFIG_TEEDEV_DMAC_CACHE_PAGES=4
CONFIG_MAIN_STACK_SIZE=32768
CONFIG_CMRT_SID=y
# make RELEASE_BUILD=1 unsets these
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_DEBUG=y
CONFIG_THREAD_MONITOR=y
