user_footer = footer.json
user_name = sample_root
user_libs = -lcmrt_v1 -los -lc
user_includes =
user_objs = sample_root.o
user_cflags = -Wno-format -Wno-incompatible-pointer-types
user_ldflags =

pubkey = pubkey.pem
root_json = new_root.json

include ../../../common/container.mk
