user_footer = footer.json
user_name = sample_ecies
user_libs = -lcmrt_v1 -lucu -los -lc
user_includes =
user_objs = sample_ecies.o
user_cflags = -Wno-format -Wno-incompatible-pointer-types
user_ldflags =

include ../../../common/container.mk
