/*
 * Copyright (c) 2018-2023 Cryptography Research, Inc. (CRI)
 * A license or authorization from CRI is needed to use this file.
 */

#ifndef FBOOT_SYSCALL_IDS_H
#define FBOOT_SYSCALL_IDS_H

enum {
	FBOOT_SYSCALL_LOAD_IMAGE,
	FBOOT_SYSCALL_CREATE_ROOT,
	FBOOT_SYSCALL_OBLITERATE_ROOT,
	FBOOT_SYSCALL_HALT,
	FBOOT_SYSCALL_REBOOT,
	FBOOT_SYSCALL_RESET,
	FBOOT_SYSCALL_RESET_INFO,
	FBOOT_SYSCALL_GET_IMAGE_VERSION,
	FBOOT_SYSCALL_GET_ENFORCED_VERSION,
	FBOOT_SYSCALL_SET_ENFORCED_VERSION,
	FBOOT_SYSCALL_PREPARE_BOOT_BYPASS,
	FBOOT_SYSCALL_DATA_STORE_READ,
	FBOOT_SYSCALL_DATA_STORE_WRITE,
	FBOOT_SYSCALL_DATA_STORE_GRANT,
	/* Highest valid syscall number + 1.  Keep this as last. */
	FBOOT_SYSCALL_MAX,
};

#endif
