#pragma once

/*
 * Copyright (c) 2024 Samsung Electronics Co, Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
enum img_type {
	IMG_TYPE_MIN = 0,
	IMG_SBOOT_N	= IMG_TYPE_MIN,
	IMG_TBOOT_S,
	IMG_TBOOT_N,
	IMG_TBOOT_P0,
	IMG_TBOOT_P1,
	IMG_TBOOT_U,
	IMG_CP0_BL31,
	IMG_CP0_FREERTOS,
	IMG_CP1_BL31,
	IMG_CP1_FREERTOS,
	IMG_TBOOT_P1_FOOTER,
	IMG_TBOOT_P0_C3,
	IMG_TBOOT_P1_C3,
	IMG_TBOOT_U_FOOTER,
	BOOTDONE_CHECK,
	IMG_FROM_HBM,
	IMG_TYPE_MAX = IMG_FROM_HBM
};

#define ERR_IMAGE_LOAD_BASE				(0x1000)
#define ERR_IMAGE_LOAD(type)			(ERR_IMAGE_LOAD_BASE + (type))

#define CUSTOM_CMRT_COMMAND_BASE		(0x60)
#define REQUEST_CMRT_COMMAND(command)	(CUSTOM_CMRT_COMMAND_BASE + (command))

#define CMRT_MW_LOAD_TBOOT_N			(REQUEST_CMRT_COMMAND(IMG_TBOOT_N))
#define CMRT_MW_LOAD_TBOOT_U			(REQUEST_CMRT_COMMAND(IMG_TBOOT_U))
#define CMRT_MW_LOAD_CP0_BL31			(REQUEST_CMRT_COMMAND(IMG_CP0_BL31))
#define CMRT_MW_LOAD_CP0_FREERTOS		(REQUEST_CMRT_COMMAND(IMG_CP0_FREERTOS))
#define CMRT_MW_LOAD_CP1_BL31			(REQUEST_CMRT_COMMAND(IMG_CP1_BL31))
#define CMRT_MW_LOAD_CP1_FREERTOS		(REQUEST_CMRT_COMMAND(IMG_CP1_FREERTOS))
#define CMRT_MW_LOAD_TBOOT_P0_C3		(REQUEST_CMRT_COMMAND(IMG_TBOOT_P0_C3))
#define CMRT_MW_LOAD_TBOOT_P1_C3		(REQUEST_CMRT_COMMAND(IMG_TBOOT_P1_C3))
#define CMRT_MW_BOOTDONE_CHECK			(REQUEST_CMRT_COMMAND(BOOTDONE_CHECK))
#define CMRT_MW_LOAD_IMG_FROM_HBM		(REQUEST_CMRT_COMMAND(IMG_FROM_HBM))

#define RESPONSE_FAIL		(0)
#define RESPONSE_PASS		(1)
