/*
 * Copyright 2024 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * PROPRIETARY/CONFIDENTIAL
 *
 * This software is the confidential and proprietary information of Samsung
 * Electronics Co., Ltd. ("Confidential Information"). You shall not disclose such
 * Confidential Information and shall use it only in accordance with the terms of
 * the license agreement you entered into with Samsung Electronics Co., Ltd. (“SAMSUNG”).
 *
 * SAMSUNG MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 *
 * SAMSUNG SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 */

#include "../bat/bat.h"

/*
 * Register base address
 * It could be changed when BAT setting changed.
 */
#define PCIE_DBI_REG_BASE (PCIE_DBI_REG_BAT_BASE)
#define PCIE_DBI2_REG_BASE (PCIE_DBI2_REG_BAT_BASE + PCIE_DBI2_REG_OFFSET)
#define PCIE_DBI_VF_REG_BASE (PCIE_DBI_REG_BAT_BASE + PCIE_DBI_VF_REG_OFFSET)
#define PCIE_IATU_REG_BASE (PCIE_IATU_HDMA_PORT_REG_BAT_BASE + PCIE_IATU_REG_OFFSET)
#define PCIE_HDMA_REG_BASE (PCIE_IATU_HDMA_PORT_REG_BAT_BASE + PCIE_HDMA_REG_OFFSET)
#define PCIE_PORT_REG_BASE (PCIE_IATU_HDMA_PORT_REG_BAT_BASE + PCIE_PORT_REG_OFFSET)
#define PCIE_SUBCTRL_REG_BASE (IP_BLK_PRIV_REG_BAT_BASE + PCIE_SUBCTRL_REG_OFFSET)
#define PCIE_SYSREG_REG_BASE (IP_BLK_PRIV_REG_BAT_BASE + SYSREG_PCIE_REG_OFFSET)
#define PCIE_SYSREG_BUSCSR_REG_BASE (IP_BLK_PRIV_REG_BAT_BASE + SYSREG_BUSCSR_REG_OFFSET)
#define PCIE_DOE_REG_BASE (PCIE_DBI_PF_ELBI_REG_BAT_BASE + PCIE_DBI_PF_ELBI_DOE_OFFSET)
#define PCIE_IDE_APB_REG_BASE (IP_BLK_PRIV_REG_BAT_BASE + PCIE_IDE_REG_OFFSET)

#define PCIE_MSIX_TABLE_BASE (PCIE_MSIX_TABLE_BAT_BASE)
#define PCIE_MSIX_PBA_BASE (PCIE_MSIX_TABLE_BAT_BASE + PCIE_MSIX_PBA_OFFSET)

#define BLK_PCIE_INTMEM_BASE (BLK_PCIE_PRIV_REG_BASE)

#define BAR0_TARGET_ADDR		(0x10000000000ULL)
#define BAR2_TARGET_ADDR		(0x14000000000ULL)
#define BAR4_TARGET_ADDR		(0x1FF8170000ULL)
#define VF_BAR0_TARGET_ADDR		(0x8000000000ULL)
#define VF_BAR2_TARGET_ADDR		(0xC000000000ULL)
#define VF_BAR4_TARGET_ADDR		(0x1FF8160000ULL)
#define TARGET_ADDR_NONE (0x0)

#define REBELH_VENDOR_ID (0x1EFF)
#define REBELH_DEVICE_ID (0x2050)

#define REBELH_PCIE_MSIX_ADDR (PCIE_IMSIX_BASE + PCIE_IMSIX_OFFSET)
#define REBELH_PCIE_MSIX_ADDR_BAT_TRANSLATED (PCIE_IMSIX_BAT_BASE + PCIE_IMSIX_OFFSET)

#define REBELH_PCIE_MSIX_TABLE_SIZE (32)

/* PCIe IRQ NUM */
#define PCIE_PAD_PERST_N_FALL_IRQ_NUM (0)
#define PCIE_PAD_PERST_N_RISE_IRQ_NUM (1)
#define PCIE_LINK_DOWN_IRQ_NUM (2)
#define PCIE_FLUSH_DONE_IRQ_NUM (3)
#define PCIE_FLR_PF_IRQ_NUM (4)
#define PCIE_FLR_VF_IRQ_NUM (5)
#define PCIE_CORE_RST_N_ASSERT_IRQ_NUM (6)
#define PCIE_BW_CHANGED_IRQ_NUM (7)
#define PCIE_RBAR_CHANGED_IRQ_NUM (8)
#define PCIE_VF_RBAR_CHANGED_IRQ_NUM (9)
#define PCIE_PARITY_ERRS_IRQ_NUM (10)
#define PCIE_INTERNAL_ERR_IRQ_NUM (11)
#define PCIE_CBUF_ERR_IRQ_NUM (12)
#define PCIE_EDMA_IRQ_NUM (15)
#define PCIE_ELBI_RST_IRQ_NUM (16)
#define PCIE_IRQ_NUM (17)
#define PCIE_DOE_ERROR_IRQ_NUM (18)
#define PCIE_DOE_GO_IRQ_NUM (19)
#define PCIE_DOE_READY_IRQ_NUM (20)
#define PCIE_VDM_INV_RECEIVED (21)
#define PCIE_VDM_RECEIVED (22)
#define PCIE_VDI_STATUS (23)

#define PCIE_IRQ_PRIO (5)

#if defined(ZEBU)
/* For ZEBU XTOR */
#define PCIE_RC_MEM_ADDR (0x80000000)
#else
/* TODO: Need to update for silicon */
#define PCIE_RC_MEM_ADDR 0x0
#endif

/* Note: You can change these addresses for your test. */
#define PCIE_HDMA_LOCAL_DAT_ADDR_CM7 (DRAM_USER_BAT_BASE)
#define PCIE_HDMA_LOCAL_DAT_ADDR (DRAM_USER_BASE)

#define PCIE_HDMA_ELEMENT_SIZE (0x18)
#define PCIE_HDMA_ELEMENT_TRANSFER_SIZE_OFFSET (0x4)
#define PCIE_HDMA_ELEMENT_SAR_LOW_OFFSET (0x8)
#define PCIE_HDMA_ELEMENT_SAR_HIGH_OFFSET (0xC)
#define PCIE_HDMA_ELEMENT_DAR_LOW_OFFSET (0x10)
#define PCIE_HDMA_ELEMENT_DAR_HIGH_OFFSET (0x14)
#define PCIE_HDMA_ELEMENT_LL_POINTER_LOW_OFFSET (0x8)
#define PCIE_HDMA_ELEMENT_LL_POINTER_HIGH_OFFSET (0xC)

#define SET_HDMA_LUT(sid, ssid, ssidv) (((sid) << 9) | ((ssid) << 1) | (ssidv))

#define PCIE_VF_NUM_MAX (16)

/* NOTE: This could be changed according to the user scenario */
#define PCIE_DOE_DATA_ADDR (DRAM_USER_BAT_BASE)
