CONFIG_MULTITHREADING=n
CONFIG_CMRT_FBOOT=y
CONFIG_XIP=y
# make it possible to change clock frequency in sboot
CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME=y
# make RELEASE_BUILD=1 unsets these
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_DEBUG=y
