CONFIG_SUPERVISOR_MODE=y
CONFIG_MULTITHREADING=n
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_CMRT_AES=n
CONFIG_CMRT_CC=n
CONFIG_CMRT_FMC=n
CONFIG_CMRT_HC=n
CONFIG_CMRT_KDC=n
CONFIG_CMRT_KTC=n
CONFIG_CMRT_PKE=n
CONFIG_CMRT_TMC=n
CONFIG_SIZE_OPTIMIZATIONS=y
# make RELEASE_BUILD=1 unsets these
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_DEBUG=y
