# Files/directories to exclude from ALL checkpatch rules.
# One regular expression per line. Lines starting with '#' are comments.
# Patterns are matched against file paths using Perl regex:
#   $realfile =~ m@^(?:<pattern>/)@
lib/unity
drivers/rbc/registers
bootloader/cp/tf-a/include/drivers/aw/reg
binaries/3rd_party
tools/amt
.*\.md
