# Directories to exclude from the max line length (LONG_LINE) check.
# One directory per line. Lines starting with '#' are comments.
# These directories will still be checked for all other rules.
bootloader/cp/tf-a/drivers/clk/clk_samsung
