user_footer = footer.json
user_name = sample_aes_ccm
user_libs = -lcmrt_v1 -los -lc
user_includes =
user_objs = sample_aes_ccm.o
user_cflags = -Wno-format -Wno-incompatible-pointer-types -DCMRT_AES_HAS_CCM=1 -DCONFIG_USERSPACE=1
user_ldflags =

include ../../../common/container.mk
