#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>
#include <openssl/sha.h>

#include "utils.h"
#include "xmss_ots.h"
#include "xmss.h"

static void rand_hash(void *hash, const void *left, const void *right, const void *pub_seed, xmss_htree_addr *addr, const xmss_ots_param *parm)
{
    uint8_t key[parm->n];
    uint8_t bm0[parm->n * 2];
    uint8_t *bm1 = &bm0[parm->n];

    addr->keymask = 0;
    parm->prf(key, pub_seed, addr);
    addr->keymask = 1;
    parm->prf(bm0, pub_seed, addr);
    addr->keymask = 2;
    parm->prf(bm1, pub_seed, addr);
    // H(KEY, (LEFT XOR BM_0) || (RIGHT XOR BM_1))
    for (int i = 0; i < parm->n; ++i) {
        bm0[i] ^= ((uint8_t *)left)[i];
        bm1[i] ^= ((uint8_t *)right)[i];
    }
    parm->h(hash, key, bm0);
}

static void l_tree(void *pk, const void *pub_seed, xmss_ltree_addr *addr, const xmss_ots_param *parm)
{
    int len = parm->len;
    int n = parm->n;
    int i = 0;

#define PK(idx) (((uint8_t *)pk) + (idx) * parm->n)

    addr->chain = 0; // height
    while (len > 1) {
        for (i = 0; i < len / 2; ++i) {
            addr->hash = i; // index
            rand_hash(PK(i), PK(2 * i), PK(2 * i + 1), pub_seed, addr, parm);
        }
        if ((len % 2) == 1) {
            memcpy(PK(len / 2), PK(len - 1), n);
            len = len / 2 + 1;
        } else {
            len = len / 2;
        }
        addr->chain += 1; // height
    }

#undef PK
}

static void tree_hash_rec(void *root_node, void *auth_path, void *key, int leaf, int height, int curr, xmss_addr *addr, const void *seed, const void *pub_seed, const xmss_ots_param *parm)
{
    const int t = 1 << height;
    const size_t n = parm->n;
    int depth, target;

    xmss_ots_addr *oaddr = &addr->ots;
    xmss_ltree_addr *laddr = &addr->ltree;
    xmss_htree_addr *haddr = &addr->hash;

    assert(curr > 0);

    // found our depth
    depth = height - (31 - __builtin_clz(curr));
    assert(depth >= 0);

    if (curr >= t) {
        static uint8_t pk[64 * 131];

        // the pk is generated by ots
        oaddr->type = 0; // ots
        oaddr->ots = curr - t;
        // do we need sk?
        if (key && leaf + t == curr) {
            wots_gensk(key, oaddr, seed, pub_seed, parm->type);
            wots_genpk(pk, key, oaddr, pub_seed, parm->type);
        } else {
            // generate pk
            wots_genpk2(pk, oaddr, seed, pub_seed, parm->type);
        }
        // use l_tree
        laddr->type = 1;
        laddr->ots = curr - t; // ltree
        l_tree(pk, pub_seed, laddr, parm);
        memcpy(root_node, pk, n);
    } else {
        uint8_t left[n];
        uint8_t right[n];

        tree_hash_rec(left, auth_path, key, leaf, height, 2 * curr, addr, seed, pub_seed, parm);
        tree_hash_rec(right, auth_path, key, leaf, height, 2 * curr + 1, addr, seed, pub_seed, parm);

        // use hash tree
        haddr->type = 2;
        haddr->chain = depth - 1; // height
        haddr->hash = curr - (1 << (height - depth)); // index
        rand_hash(root_node, left, right, pub_seed, haddr, parm);
    }

    if (auth_path) {
        // path on current depth
        target = t + leaf;
        target = (target >> depth) ^ 1;
        if (curr == target) {
            memcpy(auth_path + depth * n, root_node, n);
        }
    }
}

void tree_hash(void *root_node, void *auth_path, void *key, int leaf, int height, int curr, xmss_ots_addr *addr, const void *seed, const void *pub_seed, const xmss_ots_param *parm)
{
    xmss_addr xaddr;
    xmss_ots_addr *oaddr = &xaddr.ots;
    xmss_ltree_addr *laddr = &xaddr.ltree;
    xmss_htree_addr *haddr = &xaddr.hash;

    memset(&xaddr, 0, sizeof(xaddr));
    copy_addr(oaddr, addr);
    copy_addr(laddr, addr);
    copy_addr(haddr, addr);

    tree_hash_rec(root_node, auth_path, key, leaf, height, curr, &xaddr, seed, pub_seed, parm);
}

// sk = idx || seed || sk_prf || root || pub_seed
// pk = root || pub_seed
void xmss_keygen(void *sk, void *pk, const void *seed, int height, int layer, const xmss_ots_param *parm)
{
    xmss_ots_addr addr;
    uint8_t *psk = sk;
    uint8_t *ppk = pk;
    size_t n = parm->n;
    const uint8_t *sk_prf = seed;
    const uint8_t *pub_seed = seed;
    uint32_t idx_len = index_length(height, layer);

    memset(&addr, 0, sizeof(addr));
    addr.layer = layer - 1;
    sk_prf += n;
    pub_seed += 2 * n;

    memset(psk, 0, idx_len);
    psk += idx_len;
    memcpy(psk, seed, n);
    psk += n;
    memcpy(psk, sk_prf, n);
    psk += n;

    tree_hash(ppk, NULL, NULL, 0, height, 1, &addr, seed, pub_seed, parm);
    ppk += n;
    memcpy(ppk, pub_seed, n);
    memcpy(psk, pk, 2 * n);
}

// sm = idx || r || ots-sig || auth
void xmss_sign(void *sm, void *sk, const void *msg, uint32_t mlen, int height, int layer, const xmss_ots_param *parm)
{
    // sk = idx || seed || sk_prf || root || pub_seed
    // where idx is in big-endian
    size_t n = parm->n;
    uint32_t idx_len = index_length(height, layer);
    uint8_t *pk = sk;
    uint8_t *pm = sm;
    uint8_t *seed = sk + idx_len;
    uint8_t *sk_prf = seed + n;
    uint8_t *root = sk_prf + n;
    uint8_t *pub_seed = root + n;
    uint64_t idx;

    uint8_t *r, *auth_path, *sig;
    uint8_t m[n];
    xmss_ots_addr addr;
    uint8_t key[n * parm->len];

    // copy idx to sm
    memcpy(pm, pk, idx_len);
    pm += idx_len;
    idx = decode_index(pk, idx_len);
    // update sk
    encode_index(pk, idx_len, idx + 1);
    pk += idx_len;

    // r = PRF(getSK_PRF(SK), toByte(idx_sig, 32))
    memset(&addr, 0, sizeof(addr));
    addr.layer = idx;
    r = pm;
    parm->prf(r, sk_prf, &addr);
    sig = pm + n;
    auth_path = sig + n * parm->len;

    // M' = H_msg(r || getRoot(SK) || (toByte(idx_sig, n)), M)
    parm->h_msg(m, r, root, idx, msg, mlen);

    memset(&addr, 0, sizeof(addr));

    for (int i = 0; i < layer; ++i) {
        uint8_t root_hash[n];
        uint32_t leaf = (idx & ((1 << height) - 1));

        idx = idx >> height;
        addr.layer = i;
        addr.tree = idx;
        addr.ots = leaf;

        tree_hash(root_hash, auth_path, key, idx, height, 1, &addr, seed, pub_seed, parm);
        wots_sign(sig, m, key, &addr, pub_seed, parm->type);
        memcpy(m, root_hash, n);

        sig += (height + parm->len) * n;
        auth_path += (height + parm->len) * n;
    }
}

static void xmss_root_fromsig(void *node, uint32_t idx, const void *sig, const void *auth_path, const void *m, const void *pub_seed, int height, xmss_ots_addr *addr, const xmss_ots_param *parm)
{
    size_t n = parm->n;
    uint8_t pk[n * parm->len];
    const uint8_t *auth = auth_path;
    uint8_t *hash = node;

    addr->type = 0;
    addr->ots = idx;
    wots_verify(pk, m, sig, addr, pub_seed, parm->type);

    addr->type = 1;
    addr->ots = idx; // ltree
    l_tree(pk, pub_seed, addr, parm);
    memcpy(hash, pk, n);

    addr->type = 2;
    addr->hash = idx; // index

    for (int i = 0; i < height; ++i) {
        addr->chain = i; // height
        if ((idx >> i) % 2 == 0) {
            addr->hash /= 2;
            rand_hash(hash, hash, auth, pub_seed, addr, parm);
        } else {
            addr->hash = (addr->hash - 1 ) / 2;
            rand_hash(hash, auth, hash, pub_seed, addr, parm);
        }
        auth += n;
    }
}

int xmss_verify(const void *sm, const void *msg, uint32_t mlen, const void *pk, int height, int layer, const xmss_ots_param *parm)
{
    // sig = idx || r || ots-sig || auth || ...
    // pk = root || pub_seed
    const uint8_t *psm = sm;
    const uint8_t *r, *sig, *auth, *root, *pub_seed;
    const size_t n = parm->n;
    uint8_t m[n];
    uint8_t node[n];
    uint32_t idx_len = index_length(height, layer);
    uint64_t idx;
    int ret;
    xmss_ots_addr addr;

    idx = decode_index(psm, idx_len);
    r = psm + idx_len;
    sig = r + n;
    auth = sig + n * parm->len;
    root = pk;
    pub_seed = root + n;

    parm->h_msg(m, r, root, idx, msg, mlen);

    memset(&addr, 0, sizeof(addr));

    for (int i = 0; i < layer; ++i) {
        uint32_t leaf = (idx & ((1 << height) - 1));

        idx = idx >> height;
        addr.layer = i;
        addr.tree = idx;
        addr.ots = leaf;

        xmss_root_fromsig(node, leaf, sig, auth, m, pub_seed, height, &addr, parm);
        memcpy(m, node, n);

        sig += (height + parm->len) * n;
        auth += (height + parm->len) * n;
    }
    ret = memcmp(node, root, n);

    return ret == 0 ? 0 : -1;
}
