CTOOLDIR=../common

user_name = libshsig.a
user_objs = ./src/lms.o \
            ./src/lms_ots.o \
            ./src/tinycrypt/sha256.o \
            ./src/tinycrypt/utils.o \
            ./src/xmss.o \
            ./src/xmss_mt.o

include ../../common/lib.mk
